### ISSUE TITLE
no way to remove the context menu item

### ISSUE THREAD

**Issue by WIZARDELF** [furybee/chrome-tab-modifier#101]
as an open app, tab-modifier should provide users an option to remove its context menu item.

**Comment by sylouuu** [comment]
Hello,

Thanks for the suggestion, no ETA for this.

Best

**Comment by Quenz** [comment]
I second this. I'll never use the context menu item when clicking on a page, so it's just clutter.

**Comment by sylouuu** [comment]
Duplicate of #249
