### ISSUE TITLE
Flaky behavior on Asana

### ISSUE THREAD

**Issue by cassus** [furybee/chrome-tab-modifier#105]
**Browser:** `Chrome`
**Extension version:** 0.20.0

### Expected behavior

Icon is same when I navigate to a url within a single page app and when I refresh the page

### Actual behavior

http://recordit.co/2dihxjfzwm

At second 10-11 I use the SPA navigation and the icon changes to the proper one but then changes back immediately to the previous one. When I refresh the page with that URL, the proper icon is loaded

### Steps to reproduce the behavior

I added two URLs to the rules, the url for "My Tasks" and for "Home". Then I load each page in asana SPA navigation or try by reloading

**Comment by sylouuu** [comment]
Hi @cassus,

Unfortunately SPA are not (properly) handled.

**Comment by cassus** [comment]
Do you have some pointers for me if I'd try to fix it?

**Comment by MartinLichtblau** [comment]
@cassus My [forked version](https://github.com/MartinLichtblau/chrome-tab-modifier) can do that.
