### ISSUE TITLE
Custom icons and notifications

### ISSUE THREAD

**Issue by Kalamaris** [furybee/chrome-tab-modifier#108]
First of all thanks for your work. I love the extension.

I'm experiencing the following behavior and I dunno if it's a bug or a known limitation.

I'm trying to conceal Discord as follows:

```
 {
            "name": "Disc",
            "detection": "CONTAINS",
            "url_fragment": "https://discordapp.com/",
            "tab": {
                "icon": "https://www.google.com/gmail/about/images/favicon.ico",
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": "Gmail",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
```
As you can see I'm using the default Gmail icon for the tab. The problem is that by default when there is a new message on Discord the tab shows a numeric notification. With the configuration above the notifications don't appear.

And now the strange thing. When I'm using the configuration bellow, which is using the default Chrome icon from your combobox, the notifications appear as expected.

```
{
            "name": "Disc",
            "detection": "CONTAINS",
            "url_fragment": "https://discordapp.com/",
            "tab": {
                "icon": "chrome/chrome.png",
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": "Gmail",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
```

Is this supposed to happen?

Thank you.

**UPDATE:** I've identified the problem. It appears to be an issue when using .ico files for the image. As soon as I converted the .ico to .png and used that, the notifications are appearing as expected.

I'll leave the issue open for you to decide if it's something that needs changing or not.

**Comment by sylouuu** [comment]
Thanks for your feedback @Kalamaris.

Sure it's a strange behavior. Actually I'm not sure I can do something for that. There no different process depending on the image extension.

Glad you have found a workaround. I'll close it later.

Best
