### ISSUE TITLE
Feature request, allow icon to be set from/as an emoji character.

### ISSUE THREAD

**Issue by timmfin** [furybee/chrome-tab-modifier#113]
For example, I wanted to re-use emoji characters (like 💻  or 🚧) as tab icons for websites I was developing locally or viewing in a staging environment. For now, I manually found images on the web to represent those icons, but I think it would be great if I could type an emoji character into the icon input field. Or even better, have an emoji chooser (similar to below screenshot) to browse an emoji icon to choose from:

<img src=https://user-images.githubusercontent.com/60455/35161124-43aa431c-fd0d-11e7-8b9c-cc2c875b9852.png width=200>

**Comment by sylouuu** [comment]
Hello,

Alternatively, you can use any emoji in the page title.

I'm not sure to implement this, let's see if anyone else is interested!

Best

**Comment by supersaiyansubtlety** [comment]
I would find this useful! Also, if the workaround of adding the emoji to the title is to work, you need to be able to hide the actual icon.

**Comment by sylouuu** [comment]
You can use emojis inside the title. It works!
