### ISSUE TITLE
(Feature request?) Can I make it so that the unique tab check closes existing duplicates, rather than closing a new tab I'm trying to open?

### ISSUE THREAD

**Issue by sevrlbats** [furybee/chrome-tab-modifier#115]
For all I know this is already doable, but the 90 seconds I spent poking didn't reveal it to me!

I wrote up a description of the problem below, but it's probably a lot easier to show than to tell, so here's a 90-second video demonstrating and explaining the behavior I'd like to be able to modify: https://www.youtube.com/watch?v=VDJfxAqtk70&feature=youtu.be

I've got a super simple use case for this extension--preventing myself from opening scads of Facebook and Twitter tabs across multiple open browser windows. In general, it's been a lifesaver in that respect, but there's a fairly common use case where it's not wholly optimal for me:

If I have a Twitter tab open in Chrome, then I go to another Chrome window and open a second twitter tab, it's the new tab that collapses. If it were in the first Chrome window, it would also click me over to the first twitter tab and reload it--that seems fine. But when the second tab is in a second window, the second tab shuts and the first tab reloads, but the extension doesn't haul you off to the first window to focus on that first tab. This can mean I end up poking mindlessly through endless tabs trying to find where the one that won't let me open another is.

Could there be an optional feature on the unique tab mode to cause the existing tab to close when a new one is opened, rather than trying to collapse the new tab into the already-open one?

**Comment by sylouuu** [comment]
Duplicate with #118
