### ISSUE TITLE
Unique tab w/o reload

### ISSUE THREAD

**Issue by simonschllng** [furybee/chrome-tab-modifier#118]
I was looking for the unique tab feature. I often click GMail links from my todo-list to quickly open the associated mail. This feature help to prevent having tens of GMail tabs open.

But GMail loads kind of slow, especially over slow networks. Also the current behavior of adding new tab and closing the old destroys the history (cannot go back).

Is there a way to make a click to a GMail link in Tab A to add the URL to the history of Tab B. This way GMail could read the new `#/` portion and show the mail directly.

Pasting a new URL into an existing GMail tab works great.

**Comment by sylouuu** [comment]
A workaround would be to have a checkbox like "when a duplicate tab is found, close the new one". With default to true (current behavior).

I'm not sure if this can solve your issue.

Best

**Comment by sylouuu** [comment]
Duplicate with #115

**Comment by simonschllng** [comment]
Might be related with #115 but is not a duplicate. Actually #115 wants it the other way around i.e. closing the old tab. I want to close or not open the new tab and push the new link on top of the old tabs history stack. (This should then navigate to the new location.)

**Comment by l4kr** [comment]
So which one is duplicate of which? 
Either way it would be great if pages didn't have to load twice (first time normally, then again when it replaces a tab). Is there a way to do this?
