### ISSUE TITLE
Regex Ignore Case Not Working

### ISSUE THREAD

**Issue by supersaiyansubtlety** [furybee/chrome-tab-modifier#120]
_In case of bug report, please fill this template and remove italic lines_
_Otherwise, clear all and type :)_

### Tab Modifier version

**Browser:** Chrome

**Extension version:** 0.21.0

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Expected behavior

I expect regex ignore case switches to work as they have in other applications. 

### Actual behavior

Neither (?i)expression nor /expression/i seems to make the 'expression' ignore case. Instead, the regex just fails to match the things it matched before I tried adding the ignore case syntax. 

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. Create a rule with the following regex url matching
amazon.com/.[a-z]
2. For title, enter @1
3. For title matcher, enter the following
(?i)(?:Amazon.*:)? ?(.*)
4. Save
5. Load amazon.com

Without rules, the title is Amazon: shop, etc...
With this rule, the title doesn't change
If you remove the (?i) from the title matcher of this rule, the title at amazon.com changes to
Shop, etc...

**Comment by sylouuu** [comment]
Hi @supersaiyansubtlety,

Referer to https://github.com/sylouuu/chrome-tab-modifier/blob/master/src/js/content.js#L118 should I remove the `'g'` option in order to allow you to specify any flag?

Best

**Comment by supersaiyansubtlety** [comment]
Could you parse 'rule.tab.title_matcher', checking if it ends with a slash followed by any combination of flag characters, and if g is missing, add g? And if there are no flags, wrap the regex like this '/regex/g'?
