### ISSUE TITLE
Option to only change Icon in Bookmark mode??

### ISSUE THREAD

**Issue by dagchild** [furybee/chrome-tab-modifier#132]
I was wondering if there was any chance if this amazing extension, could leave the ability to change the favicons of the bookmarked pages, but leave the tabs themselves?

I have always found the bookmarks bar cluttered and messy, with different sized icons and design types. -With your extension: I was able to change each icon in my bookmark bark into a simple coloured circle.

The problem is: now when I have open multiple tabs, I now am having difficulty differentiating between what tab is what. -It would be great to have the option to only change the icon when it is in the bookmark bar, and then not modify the icon once it is opened in a tab.

IS this at all possible? Thanks -keep up the good work!

![screen shot 2018-03-13 at 11 52 02 pm](https://user-images.githubusercontent.com/37332323/37345866-93b188a8-2719-11e8-9d6c-c786163903a4.png)

**Comment by dagchild** [comment]
Also, there isn't an extension out there that I have found that customises the bookmark bar only.

**Comment by sylouuu** [comment]
Hello @dagchild 

The icon you see in the bookmark bar is the latest found by Chrome when you have visited the website.

Not much I can do so.

Best
