### ISSUE TITLE
Improvement to Unique: Close and switch to correct tab

### ISSUE THREAD

**Issue by garfolino** [furybee/chrome-tab-modifier#133]
Hi. 

When using Unique, the tab you are trying to open a webpage on gets closed and the same link opens in the Unique tab. 

It would be useful if THAT tab would come to the front. 
People like me that has tons of tabs and windows opened, gets lost. I know its somewhere, but now I have to hunt for it! :)

**Comment by garfolino** [comment]
I actually just saw this on the documentation: "Besides the extension will not focus the original tab after closing the duplicate one.".

Is there a reason why not?

**Comment by sylouuu** [comment]
Hello,

Because every users don't want the same behavior. An extra option associated to the unique option is required to make all people happy.

Best
