### ISSUE TITLE
Feature Request: Dynamic Favicons

### ISSUE THREAD

**Issue by natepelzel** [furybee/chrome-tab-modifier#134]
I'd love to be able to use a DOM selector to manipulate the favicon URL.

As an example, I use the [UI Avatars](https://ui-avatars.com/) service for creating my favicons. The following URL:

`https://ui-avatars.com/api/?name=P&rounded=true&background=08afc9&color=fff`
creates:

![image](https://ui-avatars.com/api/?name=P&rounded=true&background=08afc9&color=fff)

I would love it if I could select a DOM element that has a number of updates and then change the favicon. Something like:

`https://ui-avatars.com/api/?name=P+{.update-count}&rounded=true&background=08afc9&color=fff`

Which may look like:

![image](https://ui-avatars.com/api/?name=P+3&rounded=true&background=08afc9&color=fff)

Also, not as important, but still worth mentioning, this could be even more powerful if there was some kind of conditional checking we could do to change other parts of the url.  Maybe like, if a DOM element exists? Perhaps in the format of:

`{.update ? ff0000 : 08afc9}`

Which could change the color of the favicon to red there are DOM elements with a class of 'udpate'

Just some thoughts.  But overall, I love the extension!

**Comment by sylouuu** [comment]
Too tricky. :)
