### ISSUE TITLE
Allow tab color to be modified

### ISSUE THREAD

**Issue by drsuess** [furybee/chrome-tab-modifier#137]
It would be useful to have a Tab Rules option to change the tab color to a user-defined hex color. This way a user could organize tabs by color groupings (especially useful if lots of tabs open in a browser window). 

The reasoning behind this is analogous to what can be done with the `<meta name="theme-color" content="#{hexcolor}">` tag in controlling the display of the "tab" color on mobile: https://developers.google.com/web/fundamentals/design-and-ux/browser-customization/

**Comment by sylouuu** [comment]
Hello,

As I know you can't set a color on a Chrome tab on desktop. Beside, Chrome mobile does not support extensions.

Best

**Comment by MarcinZukowski** [comment]
Indeed. Maybe another option is to "colorify" the icon? :)
