### ISSUE TITLE
PIN and then unPIN doesn't work

### ISSUE THREAD

**Issue by vinz486** [furybee/chrome-tab-modifier#139]
### Tab Modifier version

 `Chrome` (Linux)

**Extension version:** `0.3.2`

### Expected behavior

Disabling PIN feature should unpin the target tab.

### Actual behavior

Enable PIN. Refesh target tab: tab is pinned.
Disable PIN. Refresh target tab: tab remain pinned and can be unpinned only using right click menu on tab itself.

**Comment by vinz486** [comment]
(other than this, thank you very much for bringing a easier life to developers :1st_place_medal: )

**Comment by sylouuu** [comment]
Hello,

This is a wanted behavior. See the pin feature as a force pin state, not a standard on/off. Depending on the moment, a context, you'll be free to pin or unpin a given tab. Thats why I treat the pin feature differently.

If you are not sure you always need a given tab pinned, leave the option off and pin it manually. Besides the browser will remember itself the pinned state.

Hope you'll understand my position !

Best

**Comment by vinz486** [comment]
Oh ok. I understand. Maybe it's only a labeling matter: trigger pin mode, instead of enable pin.
