### ISSUE TITLE
Ability to disable a rule?

### ISSUE THREAD

**Issue by orschiro** [furybee/chrome-tab-modifier#143]
Hey @sylouuu,

Love your extension!

Is it maybe an idea to add a feature for disabling a rule rather than deleting it?

Thanks!

**Comment by sylouuu** [comment]
Hey @orschiro 

Thanks for your feedback. The development is currently inactive.

I can suggest you to export your rules from the settings, then delete the rule.
Otherwise, change the URL fragment with another value that cannot be matched. 👍 

Best

**Comment by orschiro** [comment]
Hey @sylouuu,

Thanks for your prompt reply! This is what I will do then. 

Hope development will get back on track one day! :-)
