### ISSUE TITLE
Using named capturing groups in RegEx for replacement

### ISSUE THREAD

**Issue by XelaNimed** [furybee/chrome-tab-modifier#145]
Hello.
First I want to thank for this extension! I have a proposal to expand the expansion possibilities. In regular expressions can use [named capture groups](https://flaviocopes.com/javascript-regular-expressions/#named-capturing-groups). The names of these groups could be used to replace the page title.

**Comment by sylouuu** [comment]
Hey @XelaNimed 

Thanks for your feedback. The development is currently inactive.

Sorry but I'm not sure to later implement this (very) advanced feature.

Best

**Comment by HaleTom** [comment]
#84 also mentions trying to access regex capture groups
