### ISSUE TITLE
Request:sort tab rules by name A-Z rather than oldest 

### ISSUE THREAD

**Issue by gifthubbro** [furybee/chrome-tab-modifier#146]
_In case of bug report, please fill this template and remove italic lines_
_Otherwise, clear all and type :)_

### Tab Modifier version

**Browser:** `Chrome` or `Opera`

**Extension version:** `X.Y.Z`

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Expected behavior

_What do you expect?_

### Actual behavior

_What actually happen?_

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1.
2.
3.

**Comment by sylouuu** [comment]
Not relevant
