### ISSUE TITLE
Chosen custom icon for a tab only visible once

### ISSUE THREAD

**Issue by zilahir** [furybee/chrome-tab-modifier#158]
### Tab Modifier version

**Browser:** `Chrome` 

**Extension version:** `0.22.0 `

### Expected behavior

When the rule is applied on a pinned tab, I expect it to stay there all the time. 

### Actual behavior

The chosen icon is shown, than going to an other tab. 
Then switching back, and then icon changes back to the page's original one. 

### Steps to reproduce the behavior

1. Pin a tab
2. Apply a rule based on the tab's url 
3. Set a custom icon to the rule 
4. Go to the tab you set the rule to 
5. Refresh the page
6. See the new icon is visible
7. Leave the tab 
8. Go back to the tab the rule set to 
9. Tab icon changes back to it's original

**Comment by sylouuu** [comment]
Hello @zilahir 

Is to possible to provide the website URL? It could be related to this website because some are changing the icon back when they detect another script has changed it.

Best

**Comment by micheltomm** [comment]
I have this same issue with https://web.whatsapp.com/
It works for other websites e.g. Gmail, but not with WhatsApp.

Is there anything to be done? Thank you!
