### ISSUE TITLE
Feature Request: Add a "this rule applies to only the first tab that fits this rule" condition

### ISSUE THREAD

**Issue by navilan** [furybee/chrome-tab-modifier#160]
I want the first tab I open with a certain starting URL to be pinned, protected and renamed. The other tabs need not follow this rule. Even better would be able to state a different set of outcomes for second and other tabs.

This in combination with "Open a set of tabs when the browser starts" Chrome setting will allow me to have nicely setup browser launch experience.

**Comment by sylouuu** [comment]
Hello @navilan,

This is the default behavior.

Best
