### ISSUE TITLE
Feature: 'Random color' as an option for 'Select Icon' in Edit Rule

### ISSUE THREAD

**Issue by sean5446** [furybee/chrome-tab-modifier#166]
I would like to request a feature for a 'random color' favicon. This would include only the colored icons and not the Chrome icons. 

My use case for this is to have some basis of differentiation between lots of tabs originating from the same domain. When the page title and favicon are the same for every tab it is difficult for users to find a particular tab again. Random colors could help users to differentiate the tabs and help users remember where to find a desired tab. 

Ideally, a user would be able to right click a tab and assign it a color. Random color seems easier.

**Comment by sylouuu** [comment]
Not relevant, sorry.

Best
