### ISSUE TITLE
Apply Regex to DOM selector results for Title.

### ISSUE THREAD

**Issue by BigFatHand** [furybee/chrome-tab-modifier#181]
Hi,
I don't know if this is a problem with me or the extension (and can I just say I _love_ this extension) so hopefully you can clarify.
I have set up the tab title with {#myID} to pull some info from the page using a CSS selector.
The output of this is, for example:
`TABTITLE - 1234567`
I'm trying to use regex to remove the first 11 characters of this output - i.e the word TABTITLE, the dash, and all spaces - to leave just the number.
Nothing is working for me so the question is (or 'questions are'):
Do the _Title_ and _Title Matcher_ fields work in conjunction with one another or are they to be used exclusively, either one or the other.
Is what I'm asking actually possible? If so, where do I put my regex?
Thanks for your help, 

Matt

**Comment by sylouuu** [comment]
Hello,

There is no way to manipulate a value retrieved by a selector. Alternatively try to find a CSS selector where there is only the value you need.

Yes title and title matcher are working together like: `{#myID} - Hello`

Best

**Comment by BigFatHand** [comment]
Hi sylouuu,
Thanks for the quick reply.
The only place that appears is in the "value" parameter of form #myform
I don't think there is a way to address that?  
Thanks again for your help

**Comment by jesse9212** [comment]
> There is no way to manipulate a value retrieved by a selector

Is it possible? Would be an amazing feature!
