### ISSUE TITLE
Feature Request: Use Bookmark Names for tab names

### ISSUE THREAD

**Issue by drewmie** [furybee/chrome-tab-modifier#182]
Feature Request: Use Bookmark names for tab names.  A tab rule would override this behavior.

Benefit #1: People already use Bookmarks extensively.  This would allow users to rename tabs by simply adding a Bookmark and naming it, without ever going into Tab Rules.

Benefit #2: This would automatically allow different tab names for different Google users, since every Google user signed into Chrome has their own Bookmarks.

Thanks.  I love Tab Modifier!

**Comment by sylouuu** [comment]
Duplicate of #229
