### ISSUE TITLE
Does not work on Chrome 75.0.3770.100 Mac Mojave 10.14.5

### ISSUE THREAD

**Issue by bluefire0** [furybee/chrome-tab-modifier#190]
_In case of bug report, please fill this template and remove italic lines_
_Otherwise, clear all and type :)_

**Browser:** 
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Mac OS 10.14.5 (Mojave)

**Extension version:** 
0.22.0

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Expected behavior

_What do you expect?_
That any function of the extension would work. Nothing works, not even the built-in 'Rename-Tab' feature in the extension menu -- that rule does get created, but it doesn't work.  Have tried reloading tabs in rules and restarting Chrome; no change.

### Actual behavior

_What actually happen?_
No rule actions happen.

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. Create a rule, e.g:
Name: calendar tab
Detection: Contains
URL fragment: calendar.google.com
---Actions---
Title: my calendar
Pinned: on
Protected: on
---end of Action options---
Click Save

2. After the rule is saved, go to open Calendar tab and Refresh.
2a. If no tab already open, open the Calendar URL

_expected:_ 
After step 2/a, I expect:
1. the tab name to change to "my calendar"
2. when i try to close the tab, I will get asked if i want to close it

_actual:_
1. Tab name doesn't change
2. Tab closes with no warning

**Comment by sylouuu** [comment]
Hey @bluefire0 

I have the same setup and it works well: 

![Capture d’écran 2019-07-12 à 09 28 37](https://user-images.githubusercontent.com/2300259/61110403-832fd100-a487-11e9-8c4d-b357f019d5f6.png)

You can try by importing my rule:

```json
{
    "settings": {
        "enable_new_version_notification": false
    },
    "rules": [
        {
            "name": "cal",
            "detection": "CONTAINS",
            "url_fragment": "calendar.google.com",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": "my calendar",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
    ]
}
```

Can you just set the title and leave other actions as default?

Can you open the Chrome Console to check if any error is raised?

Best
