### ISSUE TITLE
Hide Braces Syntax When No Result Found

### ISSUE THREAD

**Issue by HenryTheVacuum** [furybee/chrome-tab-modifier#193]
Here's an example. In gmail you can use {.bsU} to display number of unread mail in title. However if there is no unread mail the class doesn't exist. It would be nice if whatever braces syntax you added to the rule disappeared if no results were found (in this case {.bsU} )

**Comment by MartinLichtblau** [comment]
My [forked version](https://github.com/MartinLichtblau/chrome-tab-modifier) can do that.

**Comment by sylouuu** [comment]
Hello @HenryTheVacuum,

You can now show the unread emails in the title built-in in the Gmail settings (labs).

Best
