### ISSUE TITLE
Can't replace icon with web links, only local paths

### ISSUE THREAD

**Issue by welby12** [furybee/chrome-tab-modifier#194]
I'm running Chrome 77.0.3865.90 and Tab Modifier 0.22.0 on macOS Mojave 10.14.6 (18G95)

It won't load valid external links to replace the icon for a tab, have only had success with DataURI links to this file stored on a local hard drive. 

https://i.ibb.co/PCzs78q/icloud-calendar.png

Icon shows up fine in the Tab Modifier extension, but when I reload the tab it always looks like this
<img width="41" alt="Screen Shot 2019-09-23 at 11 44 51 AM" src="https://user-images.githubusercontent.com/13987200/65453201-90f2c280-ddf7-11e9-943f-a8ff4e91b560.png">

**Comment by sylouuu** [comment]
Hi @welby12 

I tried and I can see the new tab icon. Here is my exported rules if you to try an import:

![Capture d’écran 2019-11-27 à 11 12 16](https://user-images.githubusercontent.com/2300259/69714510-cde47980-1106-11ea-9a0c-2d462873623e.png)

```json
{
    "settings": {
        "enable_new_version_notification": false
    },
    "rules": [
        {
            "name": "gp",
            "detection": "CONTAINS",
            "url_fragment": "gp.test",
            "tab": {
                "icon": "https://i.ibb.co/PCzs78q/icloud-calendar.png",
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": null,
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
    ]
}
```

Best

**Comment by jokasman** [comment]
I also cannot replace the tab icon with a web link. The only success I had was with the list of icons that already comes with the Tab Modifier extension.

Here is my code:

<pre>
{
    "settings": {
        "enable_new_version_notification": true
    },
    "rules": [
        {
            "name": "test",
            "detection": "CONTAINS",
            "url_fragment": "https://github.com/furybee/chrome-tab-modifier/issues/194",
            "tab": {
                "icon": "https://i.imgur.com/AsbEokN.png",
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": null,
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }        }
    ]
}
</pre>

O Chrome is updated.
Versão 119.0.6045.124 (Compilação oficial) (64 bits)

![image](https://github.com/furybee/chrome-tab-modifier/assets/150241824/63427a50-1c25-4213-845b-baac2f71751a)
