### ISSUE TITLE
custom icon does not work on web.whatsapp.com

### ISSUE THREAD

**Issue by annie-may** [furybee/chrome-tab-modifier#196]
Hi there

Lovely extension but at the moment it does not convert the whatsapp icon (it does convert the title). 

For the rule, I have specified title (works) and icon (does not work) only.

Chrome version: 79.0.3945.117 
Tab modifier version: 0.22.0

many thanks.

**Comment by hvarday** [comment]
+1 

Hi @annie-may , I have the same issue.

My use case being - remove the Whatsapp Web icon so that it does not show the "number of unread messages" to reduce distraction.

What's your use case for removing the Icon ?

**Comment by hvarday** [comment]
**Update:**

For me the icon got updated after I opened the link for the Whatsapp Icon link for 1 unread message - https://web.whatsapp.com/img/f01_78cd893586564a736b94f919cd2851f7.png 

See if after visiting this you are able to see the icon change
