### ISSUE TITLE
Not working on chrome Mac

### ISSUE THREAD

**Issue by services5** [furybee/chrome-tab-modifier#197]
_In case of bug report, please fill this template and remove italic lines_
_Otherwise, clear all and type :)_

### Tab Modifier version

**Browser:** `Chrome` 

**Extension version:** `0.22.0`

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Expected behavior

_What do you expect?_

### Actual behavior

_Nothing happens on mac_

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. not working on mac (tab titles)
2. tried it on windows, working perfectly
3.

**Comment by sylouuu** [comment]
Hello,

Closing for not enough precisions. Feel free to reopen if you can add more information.

Best
