### ISSUE TITLE
Would it be possible to use on-page content to define the Tab text? 

### ISSUE THREAD

**Issue by ElvisofDallas** [furybee/chrome-tab-modifier#198]
I have a large number of pages that use code to change the content so the URL remains the same, but I need to have the tabs change based on content on the actual page.

If this is something I should pull and work on myself, I can, but if someone know of an easy way to implement, that would be appreciated too. Also happy to contribute to the project $. 

Thanks!

**Comment by sylouuu** [comment]
Hello,

Can you describe an example on what result you expect?

Bests

**Comment by OneAmperio** [comment]
Hello
I wish I could do that.
Example: I have the following line of a web page (Facebook) taken from the option "right click, search".

<div dir = "ltr" class = "linkWrap noCount"> Roberto </div>

Could I have the name of the tab with the name Roberto?
Example:

Title
Test {call of the text "Roberto" indicated on the line of the web page}
 
Final result of the tab:
Test Roberto

Thanks so much for the help and response :)

**Comment by BevansDesign** [comment]
Looks like that's a feature of the extension already.

For Amperio's code above, you would use {.linkWrap} in the title (including brackets).

**Comment by sylouuu** [comment]
Hello,

Closing for not enough precisions. Feel free to reopen if you can add more information.

Best
