### ISSUE TITLE
Search and add specific keyword to title

### ISSUE THREAD

**Issue by Survap** [furybee/chrome-tab-modifier#199]
Hello!

Sorry to bother, I'm trying to search for an specific keyword and put that into the tab title. I've tried the current method, which uses {selector} to inject it to the title with no success.

Is this actually possible? If so, I'd like to use it in 2 different scenarios:

A. Keyword **never changes** on the specified URL, but it's inside a huge wall of text. 
B. Keyword **changes** inside the URL to a random fixed value (only 5 random fixed values)

Thank you!

**Comment by sylouuu** [comment]
Hello @Survap,

Please paste the HTML source code and give the rule you have tried.

Feel free to reopen the issue if needed.

Best
