### ISSUE TITLE
Add handling js code in title

### ISSUE THREAD

**Issue by KamilKot95** [furybee/chrome-tab-modifier#202]
Hi, I have an idea to improve the extension. And I already prepared code to handle it.

We can't display modified text from a side in the title.

I noticed that it is missing feature during prepare a rule to GitLab MR page. Let's look at the image. It is already with the added feature by me.

<img width="683" alt="Screenshot 2020-06-27 at 18 50 44" src="https://user-images.githubusercontent.com/18318153/85928141-23565400-b8ab-11ea-8d32-5cf611243d2b.png">

How I did it?
I added handling JS code in the title field in a rule config.

Title:
MR - $2 %"{.gfm.gfm-issue.has-tooltip}".match(/#[0-9]+/)[0]%

As you can see, I added a special character %. Everything between "%" is executing with JS eval function.

@sylouuu What do you think? I wanted to create a branch and a merge request, but I don't have access.

**Comment by KamilKot95** [comment]
If you like it we need to find a better special key. Maybe ${<content>}.

**Comment by prastut** [comment]
@KamilKot95 I would love to see a forked version where you have added this.

**Comment by SimplyAutomate2021** [comment]
@KamilKot95 I would really love to see a forked version of this as well. Will you share the code? Maybe make a pull request.
Thanks
