### ISSUE TITLE
Opens double of every tab - Is there a fix?

### ISSUE THREAD

**Issue by janis01** [furybee/chrome-tab-modifier#203]
I am a new user and when I first set up Tab Modifer, all went well and I was thrilled.  But the next day I noticed that the line-up of tabs, properly opening, repeated. In other words, they did NOT repeat 1122334455  but instead repeated 1234512345.  The first tabs are all pinned properly and in the right order.  The repeat tabs are not in the right order and some are pinned, others are not.  

I using the version 0.22.0 of Tab Modifer (I downloaded it from the Chrome Extensions}.  
I use Chrome version 84.0.4147.89 (Official Build) (64-bit) which is current with updates.

### Expected behavior  
_What do you expect?_  I expect just one of each tab to open  1 2 3 4 5 6 7 8

### Actual behavior

_What actually happen?_  After the tabs have opened, a second set opens   1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. My computer is turned off. I boot it up to the desktop.

2.  I click on Google Chrome and the tabs begin to populate at the top.  I wait.

3.  When the tabs have loaded, I see there is duplication of each one.  I manually close the extras. If any are pinned, I manually unpin them.

I have the tabs listed in Chrome Settings --> On StartUp.  I added the pages. With all the pages loaded, I have chosen the Use Current Pages.   I close settings.

I reboot and at the desktop, I click to start up Chrome. I then open Tab Modifier and set up the rules. I refresh. 

I shut everything down and when I reboot, I have double the tabs.

**Comment by sylouuu** [comment]
Hi @janis01 

Can you export your tab rules and paste the content of the JSON in a new comment please?

Best

**Comment by janis01** [comment]
Thank you.  I teach at 2 different schools and each school uses Google Enterprise.  I also have a personal gmail address. That means I have 3 distinct Google accounts.  I have on my notebook a different Google icon to access each distinct account.  I am sending the json file for each one. The three Google accounts are:  CACC, personal, and UIS.

Here is the **CACC exported file**:

{
    "settings": {
        "enable_new_version_notification": false
    },
    "rules": [
        {
            "name": "Google Calendar",
            "detection": "CONTAINS",
            "url_fragment": "http://www.google.com/calendar/",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "Calendar",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "Gmail CACC",
            "detection": "CONTAINS",
            "url_fragment": "https://mail.google.com/mail/u/0/?tab=wm&ogbl#inbox",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "Gmail CACC",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "TeacherEase",
            "detection": "CONTAINS",
            "url_fragment": "https://www.teacherease.com/",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "TeacherEase",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "Cisco Networking Academy",
            "detection": "CONTAINS",
            "url_fragment": "netacad.com",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "Cisco NetAcad",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "DropBox",
            "detection": "CONTAINS",
            "url_fragment": "www.dropbox.com",
            "tab": {
                "icon": "https://uc37b40e8c1a1c30c9e1d730782d.previews.dropboxusercontent.com/p/thumb/AA3tPSAOC52fmk9IfbQQtctrvAB4QRpUHVCvt-7Ro8_adfFj66JLKYp2gJEq66vLH1YhIYYcDAblgzkFfmK5HI3igevpUAY6feB5INyUIvkHgzdF79cVDpZEMBoDWk04CtfOUSHqH_dDNW4nJeI2oa6Mt5yjUxb1yG7R5XFUbe3q3K-Pi5YXreou-VRwQ72QnIPdaHBQ2-3hhMHSNsR_qIBYDK4el9-LNsogudrprg73JaAamft7-GfL9JzvIs_qIupwqllc4KNR0_1n4u0oSc9cfSzIUtE3hsNOz-kxwgLLCJxEGCE1_tcc6zF8S9rcYsW792_4Y-iCS67qkw5fpLExL_6n3p80YFZXO90DEsn9EQ/p.png?size=178x178&size_mode=1",
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "DropBox",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "Google Drive",
            "detection": "CONTAINS",
            "url_fragment": "https://drive.google.com/drive/my-drive",
            "tab": {
                "icon": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAGQAZAMBIgACEQEDEQH/xAAbAAACAgMBAAAAAAAAAAAAAAAABQEEAwYHAv/EAD4QAAECAwUFBAgEBAcAAAAAAAECAwAEEQUSITFBE1FSYXEGIkJiFBUjgYKRocEWMlSiB3Kx8CQzQ2PC0eH/xAAbAQEAAgMBAQAAAAAAAAAAAAAAAgYDBAUBB//EACoRAAMAAgEBBgUFAAAAAAAAAAABAgMRBDEFEyFBUpESFGGB0SIyQlHB/9oADAMBAAIRAxEAPwDtOqsvPz6RHDv8HIc4NB+3y9YN+7xDi6QAGlFcNe9zPKJxvDjpgdKRGNRv8J4RuMBpdOBu6pGZO+AK0/OyshLbaaXs2b4TjneJwjz6yZrU3rxwOGkc/wC3NsesbSMo0sKYliUkjJa9T7svnDDsxaPpkjsXVVeYokniToftHO5+fNhn48fTzMPE5OLNyHhf2/02/wBYy+VF0H5cI9tTzLqwgXgpf5qjOE0FSMQaEZRyZ7XzpretHXfEjXgbFqmnwcusGF01y8W8nlGGUfEwxe1yWNSYz41BGfhOiRziyY7nJKuejOfUuXph3rw4vCdAIju3TwVy1rBhQ4G7qnUmJxrn3uLSkTPDyu7X2gUVeXKCPSb1O4sIG5WcEAR19/ng+2R4OsH0/wCEH9044ANCKYap4ucI+19s+qLLUW1/4p7uMkeHefcP6iHalBKSpSglIFSs+ARyDtPa5ti1XH0k7BHcZHl39TnEaekaXO5Hc4tLqxZFqzJ5dnzrcympAwWkeJJzEU6xmk5Z6emmpWWF515V1I+/TWNepVpy+jK/iu4tVHU6U04h1tDjagpCwFJI1Bj0Yymym7MkpZmWqpptNwqPiOZPvNYwxVOVgrBlcM+iYLeTGqfUtWe/sHxU0SrAndzh1QbuqePnGtw4s2Y2zN1R76MLx0EdbsjlePc19jW5eL+aLmNc8dF8PKDDhw4Oe+D4fg4ucHxfH9o75ogaE95BcPEIID/PsvLBABu+nng+m88EG+vxeXpGKafTKyzkw4FFDSCuiRUqAFct8DxvS2ap/EO2fRJJNnMKo9MirlD/AKf/AL/3HOKxYtS0HbUn3p18991VaVwSNAOQEVYwU9sq3K5DzZXXl5HqsdA/h1Y2zZVa8wkhTlUS9R4dT78ug5xo9ly7E3aDDE0+lhhSvaOKNKJ19+gjrLNu2IwyhpqelkIQkISgKwSkZUjNixXX6kmbfZuKXfeW+nQaOIS4haFpwIoU8POEDzZadUhWYOe+L34hsfS0mKDI3sT1ijaVr2Q8lLjdoMFxOBF7TlGh2p2dlzY/jmH8S+nkWXjcmIrTpaZ4jLLPFh5KwKjIjeIW+trP/VtfOA2tIfq2vnFejh8yKVTjra+j/B0HnwUtOl7o3BKkqQFBXdON/dyica0u48GnWE9gWnLzRVLMPJdWgXkpScKV1hxhTPu8Wtd0W3FVVCdy0/6fgcukk/B7QDkgODiMTEKIB76yg8KcoIyEQ4f2c+sByNcvFy6QcX7ufSDh3+Hl1gDkPbCxvU1rrS0mkq/VxjcBqn3f0IhHWOwdrLGFs2Q60gD0hs7RonVe7oco48QSq6QQdQcCIjGGsmRRPmVvmcV482p6M9tVrf8AlF5KqisVkJoIzIwi44MSxY1E9ET0pWkZIIisEZtHgRBgh/2Nsn1jae2eTWWlaLX5leEff3c4x5sixQ7ryJxDulKNv7H2SLMsq+8mj8xRb29PCn3A/MmH3evaX6ZaUiMbwNRf0OlOcGF3I3K5a1io5MlZLd11Z3YlRKlEpvEezCSnerOCPK7tfaAqVvTlBECROVP2+XrBv3eIcXSMU1MMyjDj8y6ltpAqtajQKhZK9prKmZhplD60KdN1lTrK0JJ3AkUMAON1M/CeHkYQzfY+xJqbdm3pVe0dUVLCXVJqo5kAHXP5w+wplXenj5wfFjx7uUSm6h7l6ZGomv3LZrw7FWGMBLuVzvbddP6xP4NsP83oztDkNsuo+sbBhw4cH3jBOzbMjLLmZp3ZtIpeduk1qaUwjL81n9b9yPc4/ShP+DbEy9HcwzO3Xj0xg/Btifp3ccvbL7vXGH+Gg6Dg5ximZqXlG9pNPtsoJpfcUEhZ3Yw+az+t+553OP0oS/g6xP07uH+8rvdMYaWZZsrZbHo8kjZpKiqpJJqd5PyjNLTUvNIvyr7TycgptYUEfKJeeZl29o+4htuoBvqCQok0GfOI3myWtVTaJTjiXtIyUFDgbuqdSd8TjXMXuLTpEe/Hj4eUGFPy4cH3jETJFQO4sNjhVnBEGniRtDxCCANe7SJQ5a9htTdPQlPrvpV+UOXe4D74sW9P2hZ6HJhuQlnpNlvaFx2YuEkbhTpTrDGfkpa0ZVUtONB5pehwvHfXQ84WI7MSd9BmZmfm2myClmZmCttsjLu0xgCrK2jbNsvOpkHJaREs23fDrZcJcUgKKcxRIrSucY5S3bQtkycrIBiVfcZW7MLWm+BdWUdwVxqRqcBDSfsGWnJpUyl6blnnUhLnoz1zbpGV7+6xD3Z6QXLyzcuX5T0VJQy/LOFC0A5iutecAKzb1pAqs0iWNpicEqJmh2ZSU3r13fTSufyij2jmrTRLWjZlouy7yESjb6FNN3CaupFSKmmsN7SsVmVsjYysi/Nq24ecuv0fvaupVqsbsIoWZYXrCZnnptFoolH2EMhc6v27qgu8TyGAFIAl637UmLQmkWWErMu+WkSwlysvXTQla6gIGdOkNrdG0csUPNgXp5N5tVDc9mvA6GJm+zkpMzLzoem2A+azLDD9xCzvI39KRctCzmZ5phtxx5vYuBbS2l3VFQBAx6EwAutJhmStiypiTaQ2++6pl0NgJ27VxRJUBnQhJrz5xSE9aL9gsWjPehONvLYCWNhUN1dSKkk4mhNN2GcO5OyJaVfVMFT78xduF+YdK1Np3Jrl7oPVEsLMZs0BzYNFCkC9iq6oKFT1AgBeu15tLL0qpLRtJM6JVtBT3VhXeS5SuVypPNJiintBaTwVOS6VrbDpSiXTIOqK0BVP80YXszlQZRsCrLlVWqm1CFekJb2d+uAz034kV3GK5sGX2qih6bbZU7tVSaHqNFVa13ipxoDSAGtfOW/LSCJxP5UBwcRggCDlXi+nSDU+XDr1gggCaab8enSDWu7CmhgggAu+Gp311g50z00EEEAFKGlThrv6wHMeYfLpBBAARQfy/XrBSppxY13dIIIANL27CmhgpiE44411gggCAL+N5SeSTQQQQQB//9k=",
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "My GDrive",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "LLCC",
            "detection": "CONTAINS",
            "url_fragment": "https://www.llcc.edu/my-llcc/",
            "tab": {
                "icon": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAH0AfQMBEQACEQEDEQH/xAAcAAACAgMBAQAAAAAAAAAAAAAABwUGAQQIAgP/xAA7EAABAwMBBAUJCAIDAQAAAAABAAIDBAURBgcSITETIkFRcRQVMzU2YXKRsSNCU1Ric4GSMlI0VfAW/8QAGgEAAwEBAQEAAAAAAAAAAAAAAAQFAwIBBv/EACkRAAICAgEDBAIBBQAAAAAAAAABAgMEETESITIFEzNRIkEUFUJSYXH/2gAMAwEAAhEDEQA/AHigAQAIA8SSMjaXPcAB3oS2BUdR7QLVaN6NjxNMPugp2jBss7vsL2ZEYi9um1K51BIpB0TT3hVK/Ta48iksqT4KrXalulcSaicOz+lORx648GDtk+SLklfI7eeclapJHGz609bPTkGJwGPcvHBPk9UmidtuuL1QEdHUAt7t1Lzw6p8o0jfOPBcbLtYeHtZcYcg839yRt9MWtxYxHL+xj2XUVuvEIfSTtJ7W55KVbROp6khyFkZ8EuDlYmgIAEACABAAgCPvF4pLRTOnq5GtAGQM8StKqpWPUTic1FbYlNX7Qay6zSRUbnRU4dge9X8bBjWty5J1uQ59kUiSR8jy6Rxc49pVBLXAszwgAQeAgAQBlAAg9Nu33Krt0okpZnMIPIFcTrjNaZ1GTjwNvQ20aOrLaO6ndk4BrzgAqLl+nuP5QHqcnfaQy4pGysa+Nwc0jII7VKa09MdR7XgAgAQBH3y6wWihkqqhwAaDgE81pVU7JdKOJzUFtnPurtUVV+rXl0hEIOGtBX0uNjRqiuxKttc2V1NGJhAAgAQAIAEACABAAgD0x7mODmEtcORCGk+T0amzbXDmvZbrjJlp4NcSo+dhrzgPY9/9shvMcHNDmnIIyCog+ZQB4le2Nhe44AGUJbDgQ+0zVEl2uDqSGRwp4jyB5r6PBxlXHqfJLyLet6RRlQFSW0/p6sv85hod3fAz1ljdfGlbkaV1ub7FhOy7UAGT0PD3pX+pUm38WZGW3RV1uNZUUlP0fSQHDslbTzK4RUn+ziNMpNokzsuv4BP2OAO9Y/1Kk7/izKhcKOWgqn08+N9hwcJ6E1NbQvJaejWXRyZAJOAMk9iAJq0aVu91cBT0sgaeT3NwFhZk118s1jVKXCJ12y+/tYXHocAZ/wAkt/UaWzX+LMp9dSSUVU+nmxvsODjknoSUltC8lp6PlG90b2vY4tcDwIXTW+x4PbZlqjzvQCmqHkzxDtPML53Pxvbl1LhlPHt6lpl8U4aKdtKv3mixvZG4CaUYancGj3LNv9C+RZ0xOfpHukkc95y5xyV9MlrsStnhB4MjYx64kH6SpfqfxjmJ5Dqk/wAHeCgIosoeiPae8/uBUsr4YC1PnIvj/Ru8Cpy5GTmnWXtBVfEfqvq8X4kR7fNkZQUU9fVMp6Zhc9xxw7FrOagupnEYtvsObSGzejo4Y6i5N6WYjO47BAULJ9QlJ6gUKsZLvIYNPTxU0QjgY1jByaApkm5PbG0kjM/oJPhP0RHlA+DmbVvtBV/GvrMf4kRrfJkOtjgndH3iSzXmCZrsMLsP8Evk1K2to0qn0y2dIUdS2rpYp4yN17Q5fKzi4vRYT2tiU2wXE1F5FKDlsWF9B6bX017JuVLctC9VIVBB4MjYx65k+FS/U/jHMTyHVJ6N3goCKL4KHon2nvP7g+ipZXwwFaPORfZPRu8Cpy5GjmnWALtRVIHa8/VfVY3xIj2+bGrsu0rDQW9tdUxh1RJxaT2BR/UMlzl0Lgexqkl1MYLnBjS5xwBzJUxDZU7trDdmdS2aDyuoBx7h/KdrxO3VY9IXld+okNNDresjfLv+TsIJ3Q7PBbp4ke3Jm1e0KC+NnZc521ZzMHdY96t1a6F08CE977mgtDgyOHEIPToHZtcxWacjMjuMZ3ea+azq+m3sVMeXVDuJXVdYa69TTl2d4BX8ePTXonWvctkOtjMEAMjYx65k+FS/U/jHMTyHVJ6N3goCKL4KHon2nvP7g+ipZXwwFaPORfZPRu8Cpy5GhCNtvnTaEKdwzH0vXX0fue3i7JfT1XaHxTwsp4I4oxhrGho/hfOSe22VEtLRU9bXSZ08NmonYnnGXEcw0p3FqWnZLhGF0n4omdPWGls1G2KNgMpHXeeJJWF18rZbNK61BEpPjoJPgP0WMeUds5m1b6/q/iX1eN8SI1vkyHW5mZQBedE3w261vi38ZkJ7EhlU9c9jVM+lFJmeZJC53Mp5LSFmfNengIAZGxj1zJ8Kl+p/GOYnkOqT0bvBQEUXwUPRPtPef3B9FSyvhgK0eci+Seid4FTlyNCp0ZAJtf3B5x9ngj5lWMmWsaIjUt3MbKjD4urOfLtotSZ+sYYyG59xVS38MVa/YpDvc9jEPJSxsUuvNfXCgustDQkNazgc9qtYmDCcOqQhfkSUtIVlbVSVtU+omOXv5qvGKitISbbe2fBdHIIA2aeofEzdaeGVzKO2dJ6CvgNPUujIxhEHtbCS0zWXRyCAGRsY9cyfCpfqfxjmJ5Dqk9G7wUBFF8FD0T7T3n9wfRUsr4YCtHnIvxGWkd4U0bF1RUEdk147rf8ALIA4/wDu9VJz93G/4KRj0W/9GMpY2L+SI2PXoqHZ6GpjxvHvJ5Kkn7uNr6FNdFu/sv8AkEcO1TRso2rtn1Hep5KxjujmwSfeqONnSrXSxW3HUu4kbvReb7hNS5z0ZxlX659cVImzWno0l2cggCUtlvdVQF4bnjhYzn0s0jHZJbQaA0Go52Y6uBhZ4c+upM6vj0z0VpNGJhADI2MeuZPhUv1P4xzE8h1Sejd4KAii+ChaKe1up7zvOA+0HNUsr4YCtPnIvnSx/wC7fmp2mNbKVtBhMElFd6c5NK/efhP4b2nW/wBi9601JFstNay4W+CoYc77AT44SVsHCbibwl1LZp6lszbtRlrMNnZ1o3e9aUW+3L/RzZDqRD2bUklDu0F9b0UjOqJSOq7+Vvbjqf51mcLOn8Zlm8spqimkdBPG9u6eLTnsSnRKMu6NupNdjm3Vhzf6sj/dfVY/xIj2+TIdbGZlADW2a2HyuxPlkHEyHCj51/TZofx69xDbPaHB8VfGzIP+R7kemWrTizzLj+xUqwJGEHgyNjHrmT4VL9T+McxPIdZG8COwqAUim1eheluE1ZTXCenfKcuDE/HN1FRlHehd4+3tM8f/ABFX/wB5V/NH82P+B57D/wAjxPoKeeJ0U15qnscOLSea9jnJPaiePHb/AGa1jrZdIV4tFwLjSuP2Up5ZXdsFkx9yPJ5CTqfS+BgRyMkYHxuDmniCO1TGtdhpPZp3O00V0iMdZAyThgEjktK7Z1vcWeSgpclTqtBvgikNBdKiJuCdwHgnY5u/KIu8fXDErfYH010nhkkL3Ndxce1XqpdUEydNakR60OD6QROnmZEwZc84AXjaS2z1HSOi7b5tsNPFjDnNDiF8tlWddrZYpj0w0bOqLTHeLRNSvbxLeqe5cUWuqakj2yHXHRzbdaGS3V0tNKCCx2BkL6quanHaJEo9L0aa7OBjbHJGR3iQyPa0bp4uOFL9TTcOw5iP8h0eVU/48f8AYKF0S+ijtB5VT/jx/wBwjol9BtB5VT/jx/3COiX0G0HlVP8Ajx/3COiX0G0R95orbeKUwVUkTv8AV2+OqVpVKyt7SOJxjNaZUXVd10m8Bsray3jtL+LAnuivI/WmL9Uqv9osdm1lZ7q0dFUtY/7zX8MFK24ltfKNoXwl+yWlraV8Em7URHqn747lgoS3waNrRzbqsg36rIwRvdi+qx/iRHs8mRC2OC9bL9Om6XVtVM09FCcjhzU/Pv8AbhpfsZx6+qWx8tY1rQ0DAHIL5x9+SoejxQAsdqWjjVxG5ULftG8XtA5jCren5fS+iQlk07/JCaexzHljxhwOCCrqe1snn2pKyekeXU8jmE9xXMoKXJ6pNcG35+uf5p/zXHsV/R17kvsPP9z/ADT/AJo9iv6D3JfYef7n+af80exX9B7kvsPP9z/NP+aPYr+g9yX2Hn+5/mn/ADR7Ff0HuS+zDr5cXjdfUucO4oVMF+jz3JGj00m+Xh7g48yDhaaRztm3HeLhGzdZUyAd2Vw6oP8AR11y+zTkkfK8vkOXHmV2lo5ZvWS0VN4rY6amacuOCcclnbbGqO2dQg5PSOitLWKGxWyOniA38ZccduF8xkXu6e2V661COiaWBoCAPEsbJWOZI0Oa4YIPavU2u6DQo9oOgHNe+vtjMt5uaFaw87f4TEL8f+6IrJGOje5j2kOacEFWE98CJ5QeGEACABAAgAQAIAyg9JCy2eqvFW2npI3OOeJA5LK22NUds6hByekPjROkKewUjXPaHVDhxcexfO5eXK6WlwVKaVBFsSZuCABAAgDDmtcCHAEHmCgCiau2e0l3356QCKYnPDkqONnyr7S7oVtx1LuhR3zS1zs0zmzwPcwffA4K1VkwtXZiE6pR5IPGOfBMGYIPDCABAGUAe4YZJ3hkTC9x5ABeNpLbPdF20xs6uF0LZatphi7ndqQvz4V9l3Ga8eUuRw6d05Q2KnEdNGN/Ay8gZUO/Inc9soV1xguxNLA0BAAgAQAIAEACANeqpIKthZURNkbj7wyvYzcX2PGk+Sp3fQFlqw55jdGf0cE7XnWx7C8seEu4uNQaRoLc53QvlOO8qrTlTnyKTpUeCm1UDYpC1uce9PRe0Lvsblst8VU5okLuPcVxObidRjsYendAWqrw+V8pPipl+dZHgbrx4sv1p0naLbjoaZrnDkXBTbMq2fLGo0wjwTzGhrQGgADkAlt77mp6QAIAEACAP//Z",
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "My LLCC",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "Google Search",
            "detection": "ENDS",
            "url_fragment": "www.google.com",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "G Search",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
    ]
}











Here is the **personal exported file**:

{
    "settings": {
        "enable_new_version_notification": false
    },
    "rules": [
        {
            "name": "Google Calendar",
            "detection": "CONTAINS",
            "url_fragment": "https://calendar.google.com/calendar/",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": "Google Calendar",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "Gmail JRR",
            "detection": "CONTAINS",
            "url_fragment": "gmail.google.com",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": false,
                "title": "Gmail JRR",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "Dropbox",
            "detection": "CONTAINS",
            "url_fragment": "dropbox.com/h",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": "Dropbox",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "NYTimes",
            "detection": "ENDS",
            "url_fragment": "https://www.nytimes.com/",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "NYTimes",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "O'Reilly",
            "detection": "CONTAINS",
            "url_fragment": "www.oreilly.com",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "OReilly",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "NYT Mini Crossword",
            "detection": "EXACT",
            "url_fragment": "https://www.nytimes.com/crosswords/game/mini",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "NYT Mini Crossword",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "Washington Post Games",
            "detection": "CONTAINS",
            "url_fragment": "https://games.washingtonpost.com/games/daily-crossword-mini/",
            "tab": {
                "icon": "washingtonpost.com/default.png",
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "Washington Post Games",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "Google",
            "detection": "ENDS",
            "url_fragment": "www.google.com",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": false,
                "protected": true,
                "title": "G Search",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
    ]


}











Here is the **UIS exported file**:

{
    "settings": {
        "enable_new_version_notification": false
    },
    "rules": [
        {
            "name": "Google Calendar",
            "detection": "EXACT",
            "url_fragment": "http://www.google.com/calendar/r",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "Calendar",
                "title_matcher": null,
                "unique": true,
                "url_matcher": null
            }
        },
        {
            "name": "Outlook Webmail",
            "detection": "CONTAINS",
            "url_fragment": "https://webmail.uis.edu/owa/auth/logon.aspx?replaceCurrent=1&url=https%3a%2f%2fwebmail.uis.edu%2fowa%2f%23authRedirect%3dtrue",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "Outlook Webmail",
                "title_matcher": null,
                "unique": true,
                "url_matcher": null
            }
        },
        {
            "name": "Canvas",
            "detection": "CONTAINS",
            "url_fragment": "uispringfield.instructure.com",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "Canvas",
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        },
        {
            "name": "Dropbox",
            "detection": "CONTAINS",
            "url_fragment": "https://www.dropbox.com/h",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "Dropbox",
                "title_matcher": null,
                "unique": true,
                "url_matcher": null
            }
        },
        {
            "name": "KaliLinux 2019 by Singh",
            "detection": "CONTAINS",
            "url_fragment": "https://learning.oreilly.com/library/view/learn-kali-linux/9781789611809/",
            "tab": {
                "icon": "chrome/default.png",
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "KaliLinux",
                "title_matcher": null,
                "unique": true,
                "url_matcher": null
            }
        },
        {
            "name": "UIS DARS",
            "detection": "CONTAINS",
            "url_fragment": "https://login.uillinois.edu/auth/SystemLogin/sm_login.fcc?TYPE=33554433&REALMOID=06-5e82b5bf-da22-4147-92a3-297a50ae9419&GUID=&SMAUTHREASON=0&METHOD=GET&SMAGENTNAME=-SM-VMtKKRP4QIbeH8j5F8pFZNjcFl7ogFY6A%2bxavJKIyye4kJFHglCJ8zJOCz%2bEEPcmbY7E4tzR7gCuvTj3o0aRs9KrJwaSwLf1&TARGET=-SM-HTTPS%3a%2f%2fuachieve%2eapps%2euillinois%2eedu%2fuachieve_uis%2f",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "DARS",
                "title_matcher": null,
                "unique": true,
                "url_matcher": null
            }
        },
        {
            "name": "Google",
            "detection": "ENDS",
            "url_fragment": "www.google.com",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": true,
                "protected": true,
                "title": "Search",
                "title_matcher": null,
                "unique": true,
                "url_matcher": null
            }
        },
        {
            "name": "Rule created from right-click (calendar.google...)",
            "detection": "CONTAINS",
            "url_fragment": "https://calendar.google.com/calendar/r/month/2020/9/1",
            "tab": {
                "icon": null,
                "muted": false,
                "pinned": false,
                "protected": false,
                "title": null,
                "title_matcher": null,
                "unique": false,
                "url_matcher": null
            }
        }
    ]
}


I hope I've provided the information you need.  I appreciate your willingness to help me.  Thank you very much.

Janis

**Comment by janis01** [comment]
I'm not sure what I did that caused my last added comment to close this issue. I did not mean to do that. Hopefully this comment is now reopening this issue.  I did provide the json files you requested in my previous comment.

**Comment by janis01** [comment]
Yes, thank you.  I have provided this information in a new comment.

**Comment by sylouuu** [comment]
I'm not sure to understand, I've imported the first pasted JSON, you have pasted 3 different.

What file should I try? Let's focus on one.

Side note: Tab Modifier is not designed to let you decide what tabs to open at startup, Chrome is doing that well. So I don't get it how you can have duplicates?

Best
