### ISSUE TITLE
remove a certain words from a specific title

### ISSUE THREAD

**Issue by i27i13** [furybee/chrome-tab-modifier#204]
https://duckduckgo.com/?q=testing&ia=web

When bookmarking this URL I get:
`testing at DuckDuckGo`

There are plenty of examples to add to a title of a site, but how can I for example
REMOVE:
` at DuckDuckGo`
So that when I bookmark:
https://duckduckgo.com/?q=testing&ia=web
I'd end up with just:
`testing`
as a page/bookmark title!

A million thanks in advance because I am not literate in programming languages :(

**Comment by sylouuu** [comment]
Hello @i27i13,

You can rename a bookmark. By the way, Tab Modifier does not interfer with bookmarks and will never do.

Best
