### ISSUE TITLE
Feature Request: Option to Hide Right Click Contextual Menu

### ISSUE THREAD

**Issue by jnbli** [furybee/chrome-tab-modifier#206]
I would be nice to have the option to disable the right click context menu "Rename Tab" somewhere in the Tab Modifier Settings. This is for a more minimal look. Also, most of the time I (and perhaps others) am not thinking about renaming a tab.

**Comment by sylouuu** [comment]
Duplicate of #249

**Comment by juniorchavezdiaz** [comment]
I'm sorry, but the option to hide the right click contextual menu is not available, when will it be available to hide it?

**Comment by dimateos** [comment]
Yeah everything is marked as "duplicate" of other issue but no issue remains open?
I see you moved it to conversation https://github.com/furybee/chrome-tab-modifier/discussions/277 but also mention "duplicate"

Quite confusing, may I suggest at least keeping one of the issues open?
