### ISSUE TITLE
Import and Export rules in Excel sheet for editing.

### ISSUE THREAD

**Issue by JoseOcda** [furybee/chrome-tab-modifier#212]
Is there an option to upload and download the rules for editing purposes?

In excel sheet it would work well for 1504 pages, and growing ...

**Comment by sylouuu** [comment]
Hello @JoseOcda,

You can export your tab rules settings, edit inside any editor that supports JSON format like https://jsonformatter.curiousconcept.com/ save the file with the new content.

Best
