### ISSUE TITLE
Tab Modifier - Not Protecting

### ISSUE THREAD

**Issue by Esedgwick90** [furybee/chrome-tab-modifier#213]
_In case of bug report, please fill this template and remove italic lines_
_Otherwise, clear all and type :)_

### Tab Modifier version

**Browser:** Chrome 

**Extension version:** 0.22.0

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Expected behavior

_What do you expect?_ A pop up to appear and ask if I am sure I want to close my tab.

### Actual behavior

_What actually happen?_ Nothing happens, the tab closes like normal.

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. Create rule
2. Turn on "Protected"
3. Test rule

**Comment by sylouuu** [comment]
Hi,

This is a known issue given in the README, please see #95 

Best
