### ISSUE TITLE
Help change the Linkedin page title?

### ISSUE THREAD

**Issue by jpotocki** [furybee/chrome-tab-modifier#215]
Would anybody help me setup Chrome Tab Modifier in a way to change:
**(99+) Jose Rodriguez | LinkedIn**
into:
**Jose Rodriguez Cesenas | LinkedIn**
(remove the "(...) " from its beginning, if it is there /conditional)?

I think this may be a useful thing for many users, put it to https://github.com/sylouuu/chrome-tab-modifier#examples?

**Comment by sylouuu** [comment]
Hello @jpotocki,

If I understand well, you don't need any dynamic value. So create a rule for linkedin.com and set the title to "Jose Rodriguez Cesenas | LinkedIn".

Best
