### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by artgoldberg** [furybee/chrome-tab-modifier#217]
I would use this, but am concerned that you do not have a privacy policy.

If you had a privacy policy that says you would not access web data except the data in the tabs, then I would definitely use this.

Thanks
Arthur

**Comment by mindplay-dk** [comment]
Same.

You should at least indicate on the Chrome Webstore whether or not you collect any information.

**Comment by mindplay-dk** [comment]
FYI, I poked through the code, and I don't see anything too upsetting.

It is using Google Analytics, which means it will send personally identifiable information to Google. It does not appear to be tracking anything sensitive though, just basic information about the buttons and menus you use - nothing attached to those records with any sort of information about you or your data.

I don't personally care about that, but if you hate Google, you probably don't want to use this.

And it should definitely be indicated in the Chrome Webstore.
