### ISSUE TITLE
Issue with Unique tab

### ISSUE THREAD

**Issue by dsimoes** [furybee/chrome-tab-modifier#219]
Hi,

I'm doing a 'Starts with match' and then a 'title matcher' with regex to extract keywords and rewriting the title.
So far all good.
The problem is when I try to active the Unique tab feature, it will detect everything as duplicate and close all others.
An example:

Starts with: https://<base host url for example>/code/
title matcher and rewrite will contain the <code>

Url #1: https://<base host url for example>/code/12345
Url #2: https://<base host url for example>/code/98765

So it will detect both as duplicates, even though the URL is unique and the rewritten Title will also be different.

Am I doing something wrong?

Thank you.

**Comment by sylouuu** [comment]
HI,

Since `https:///code/12345` and `https:///code/98765` are both starting with `https:///code/`, the actions will be triggered, right?

The actions depend on the URL fragment & the detection type.

Best regards

**Comment by dsimoes** [comment]
Yes, but that's the matching of the URL to trigger the rule. A rule can target multiple unique URL's.
I would expect the "Unique tab" option would try to eliminate duplicate tabs with the Exact same URL. Else what's the use-case for this unique option?

Thanks!

**Comment by skallen** [comment]
I'm not a extension writer, however, looking over the code it seems that you're not passing the criteria to the "`setUnique`" listener.  This makes it impossible (again, this is first glance!) for the `setUnique` to properly interpret the condition.  In `setUnique`, there's a simple `indexOf` check which will match any part of the string, regardless of `Ends With` or `Exact`.

Areas I am referring to are:
`src/js/content.js` - line 277 (setUnique call)
`src/js/background.js` - line 29 (setUnique listener)
 - line 43, conditional check using `indexOf`
