### ISSUE TITLE
Someone please help

### ISSUE THREAD

**Issue by KimF78878** [furybee/chrome-tab-modifier#221]
I don't actually know if anyone can help me with this but judging by how much I don't understand what anyone is talking about on this page I would assume that there is no better place to ask.  My name is Kim and I am using Tab Modifier for a new job I am starting.  I am old school.  I am 42 and am used to writing things down and making notes the old fashioned way, committing what I can to memory and then coming back to my notes for things that just won't stick.  Anyway, for this new job that I have as a CX Agent for Vacasa I will be working remotely and answering phones, emails, etc for inbound guests.  It is a very elaborate system and the company has 6000 employees managing 30,000 properties with new acquisitions and integrations all the time.  So, there is A LOT of information and things to try and remember.   Well, they recommend you don't try to remember it all.  They don't care if you retain the information basically, they just want you to be able to find it when you need it on the computer.  So, I have to get organized or die trying.  I honestly want my files and manilla folders back but I have to evolve.  This is where Tab modifier comes in....once I started messing with it, it was great.  I have my tabs saying what I want because I can have lots of tabs open at one time.  I only have one problem.   Well, I thought it was just letting me rename the tab from website one time.  After reading the thread here and from what I understand that you guys have said is that, in very simple terms, the app isn't designed to handle different pages from a single website?  
I did notice that it was only happening on the pages that are from my company "How to" website called Atlas.  It just says Atlas on the tab which is better than what it was but it would be SO much better if I could make the one say "AirBB Policy" and another one say "AirBB Refunds". or something like that.  Every one of the pages starts from the same place like "www.vacasa.com/atlas" or something like that and it seems like that is the problem but IDK.  I really don't have a clue. 
Also, from our company website we also have documents that once clicked on are Google docs and they all rename just fine.  I can send over what my tab modifier looks like if someone can look and tell me how to fix the "code" to do what I want if that is possible.  I just don't want to send over something that is going to get me in trouble with work.  Like access to the internal system if that is even possible.  I need someone that is not gonna dick me around and tell me if what I need is impossible.  Or even just put me on the path to what will work, who can help or an app that does what I want, if there is such an animal.

Thanks in Advance,
Kim F

**Comment by KimF78878** [comment]
Oh!  I am using chrome on a Mac Mini if that is important

**Comment by sylouuu** [comment]
Hello @KimF78878,

You are not writing a book, please respect the issue template.

Best
