### ISSUE TITLE
Close tab ? and alternative to this extension ?

### ISSUE THREAD

**Issue by capellavacancies** [furybee/chrome-tab-modifier#222]
Hello, is there a way to automatically close a tab after gets opened ?
and the other question is: I like thi extension but the owner stopped the developmnent, nothing against his choice.
Is there something else still getting developed ?

thanks

**Comment by sylouuu** [comment]
Hello @capellavacancies,

The only way with Tab Modifier to autoclose a tab is to create a rule with Unique action enabled and have one tab opened that matches this rule. When you try to open a new one it will be closed because the tab must be "unique".

The development may be continued.

Best
