### ISSUE TITLE
Injecting a selector for form elements does not work

### ISSUE THREAD

**Issue by tai-flywire** [furybee/chrome-tab-modifier#223]
### Tab Modifier version

**Browser:** `Chrome`

**Extension version:** `0.22.0`

### Expected behavior

When specifying a DOM selector to inject into page title (e.g. "My Page about {#inputID}") which points to an HTML input, it should inject the value of that input.

### Actual behavior

Nothing, but actually the code throws an error: `Uncaught TypeError: Cannot read property 'tagName' of undefined` in content.js

### Steps to reproduce the behavior

1. Use a page title which specifies a selector pointing to an HTML text input
2. Save and reload page

### Notes

The cause of this bug is that the function `getTextBySelector()` changes the selected element to its childNodes[0].  This works for selectors that have innerText content or whose first childNodes[] resolves to either an INPUT, SELECT or an element that does.

It's not exactly clear to me what the value of `el = el.childNodes[0]` is, however since it is existing code and changing that behavior could break many installations, I think a reasonable fix would be to test that that assignment resolves to a valid element and if it does not, since the rest of the logic will fail in that case anyway, it's safe to keep the el as the original one specified by the user.

I will try to submit a pull request with my suggestion.

**Comment by sylouuu** [comment]
Hi @tai-flywire,

Can you confirm this is the same behavior with version >1.0?

Bests
