### ISSUE TITLE
Feature: Overlay text in icon

### ISSUE THREAD

**Issue by holzkohlengrill** [furybee/chrome-tab-modifier#226]
Some webpages include text in their icons (like the number of new messages).
It would be practical if one could have a similar option for the icon like we have for the page title.

Especially for pinned tabs this is useful since no title is shown.

**Comment by sylouuu** [comment]
Hello,

Closing for not enough precisions. Feel free to reopen if you can add more information.

Best

**Comment by sylouuu** [comment]
For Gmail it's available in the settings. Otherwise look for the value inside the HTML and use the advanced Tab Modifier features to get the value.

Best

**Comment by sylouuu** [comment]
For example, see https://github.com/furybee/chrome-tab-modifier/issues/257
