### ISSUE TITLE
Unique Tabs not working with RegEx?

### ISSUE THREAD

**Issue by moti0375** [furybee/chrome-tab-modifier#228]
_In case of bug report, please fill this template and remove italic lines_
_Otherwise, clear all and type :)_

### Tab Modifier version
**Browser:** `Chrome`

**Extension version:** 0.22.0

### Expected behavior
Tabs with RegEx rule and marked as unique should have only one tab

_What do you expect?_
Expected that when set a RegEx rule with Uniqueness there should be only one tab which match the RegEx. 

### Actual behavior
The title does change which means the RegEx is matched, but when opening another tab which match the RegEx it will not close the other opened tab. 

_What actually happen?_
I've set a RegEx for some web page and marked the rule with Unique, then opened a few tabs which match the RegEx, uniqueness didn't worked. 

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. Define a RegEx rule
2. Mark the rule with Unique
3. Open more then one tab which match the RegEx

**Comment by sylouuu** [comment]
Hello @moti0375,

The RegExp does not interfer with the Unique action. It's only based with the URL fragment. It's the expected behavior there.

Best
