### ISSUE TITLE
Feature Request? Rename tab based on bookmark name?

### ISSUE THREAD

**Issue by jefferyscottsmith** [furybee/chrome-tab-modifier#229]
Hi, first I'm not sure if this is the correct place for this feature request so my apologies if it's not.

Could a feature be added which allows a variable to be referenced using the bookmarked name, which then could be used to rename the tab title? It would be very helpful and I can't seem to find this functionality in this or any of the other similar extensions for Chrome on Windows. Thanks!

**Comment by sylouuu** [comment]
Hello @jefferyscottsmith,

Your suggestion does not seem relevant.

Best
