### ISSUE TITLE
Links to specified rules in contextual menu

### ISSUE THREAD

**Issue by Raph-xyz** [furybee/chrome-tab-modifier#230]
When opening the contextual menu of the extension, it could have a list of saved rules, to open the link of that rule
I often reopen a link that is renamed, and I don't want to manage it both in bookmark and in tab modifier (my rules have to be updated sometimes)
![image](https://user-images.githubusercontent.com/23099749/139399116-c0d9047c-d01b-4806-bf93-bb26f57d676f.png)
(sorry for the french in the screen !)

**Comment by spinjector** [comment]
I agree with this request. It would be very nice to have the contextual "Rename Tab", where I could simply enter the new name, and have the settings transferred into the Rules of Tab Modifier.

**Comment by sylouuu** [comment]
Hello @Raph-xyz,

It's not possible to make the contextual menu dynamic.

Best

**Comment by Kravimir** [comment]
Syl, couldn't the [https://developer.chrome.com/docs/extensions/reference/api/contextMenus#property-CreateProperties-documentUrlPatterns](documentUrlPatterns) property of the contextMenus API be used to implement that?
