### ISSUE TITLE
How did you "lock" the support section on the webstore?

### ISSUE THREAD

**Issue by orschiro** [furybee/chrome-tab-modifier#232]
Hi guys!

I am wondering how you set up your webstore placement to disable comments there?

I also want to do this for my own extension because I never receive notifications about the "Support" section on the webstore. 

However, I cannot find any option on the dashboard to disable that section like you did. 

Thanks!

![image](https://user-images.githubusercontent.com/170947/148066264-a9579543-f6d4-4f94-8c0c-d53e6f2bf50a.png)

**Comment by sylouuu** [comment]
Hi,

Not sure it was a long time ago and the whole developer console has been reworked. I've set an "Assistance URL", maybe it's enough to disable this section: https://github.com/sylouuu/chrome-tab-modifier/issues

Regards

**Comment by orschiro** [comment]
Thanks! Do you still see "Assistance URL" in your dashboard?

I don't.

**Comment by sylouuu** [comment]
Yes, in french sorry
![Capture d’écran 2022-01-04 à 14 58 53](https://user-images.githubusercontent.com/2300259/148070016-1652ad17-4967-4472-83ce-6f7d96cb5402.png)

**Comment by orschiro** [comment]
Bummer, filled the same two fields like you did but for me comments still appear there. :(

Not sure there is anything else I can do. 

Thanks for your help!
