### ISSUE TITLE
If there is a secondary jump on the page then the plugin will not work.

### ISSUE THREAD

**Issue by godefy** [furybee/chrome-tab-modifier#234]
I have encountered this problem during use：
When a page condition is set to change the title of a specific page (either in inclusion mode or in ongoing mode), it will only work properly if the target page is opened directly on the current page. If I open more than one eligible page in the background, it will not take effect.

Later I found out that it was because the target page I wanted to open was jumped over after clicking the link.
For example.
I want "www.example.com/myname" as a condition to change the title of the corresponding tab.
Then I clicked on the corresponding link on that site, and it was not a direct link like "www.example.com/myname/. *", but "www.example.com/. *", and then about 1 second after the link, the URL will automatically change to "www.example.com/myname/. *". But the plugin does not recognize this link change, as long as I open it through www.example.com/. *, it will not work.
And if I jump to other www.example.com/myname/. * pages through this page later, it will not work properly. *, it won't work unless I refresh the current page directly.

So I can only set the condition to "www.example.com", but this condition is too broad and not exactly the effect I want.

I don't know if I can optimize it. Thank you very much.

**Comment by sylouuu** [comment]
Hi @godefy,

The entire code base has been rewritten. Tab Modifier 1.0 is now available!

Is the issue still persists?

Bests
