### ISSUE TITLE
Tab rename multiple times after changing URL in same tab

### ISSUE THREAD

**Issue by rggmiranda** [furybee/chrome-tab-modifier#235]
### Summary

When a tab changes its URL or information after being loaded for the first time it does not update its title unless it is manually refreshed

### Steps to reproduce the behavior

1. Open a new tab, the URL matches rule A -> Tab title is applied according to rule A
2. By clicking on a link inside the webpage, a portion of it changes (The webpage does not load again, only some part of it). The URL changes as well and now it matches rule B -> Tab title is not updated accordingly

**Comment by miguelfbrito** [comment]
Also facing this, it happens on GitHub for example. It properly tags when the page is opened, but navigating inside GitHub loses the matching.
