### ISSUE TITLE
Long selector chain is not working

### ISSUE THREAD

**Issue by annahri** [furybee/chrome-tab-modifier#236]
I have this selector: `#cust-info > div:nth-child(5) > div.col-lg-9.col-md-9.col-sm-9`. I've tested it in the developer console, it works but it won't replace the title as it will just print the whole selector.

![image](https://user-images.githubusercontent.com/30897918/160519850-10fde620-eef9-4e79-92e0-03468cda0b0e.png)

Am I doing it wrong?

Thanks

**Comment by SoundIKS** [comment]
I Have the same problem. 

Selector: body>app-root>app-edit>app-bar>div.flex>div.flex:last-child>div:nth-child(2)

**Comment by andrew-manger** [comment]
Ever figure this out?
