### ISSUE TITLE
How to use tab title renaming

### ISSUE THREAD

**Issue by HoorayFerSocks** [furybee/chrome-tab-modifier#237]
Disclaimer: I know very little coding, just enough to take what's out there and make minor changes to hopefully get it to do what I want. I would likely need this explained to me like I'm 5 years old...

I'm trying to use the tab title renaming for an electronic notebook (chemistry). The default names are a bit long so when I have multiple tabs open, it can be difficult to remember which is which.

The current title is something like "SMW-00001-###" where ### represents a three digit notebook page number. The "SMW-00001-" part will remain static in the title, but the ### changes depending on which page number I'm working in. I would like to truncate this title on the tab to something like SW1-### or even just ###. Is it possible for tab modifier to pull the unique ### such that each tab would display SW1-###.

For example, I would like a tab with the title "SMW-00001-661" to show as "SW1-661" and tab with title "SMW-00001-662" to show as "SW1-662"

Is this possible using this extension? If so, what do I put in the Title and Title Matcher fields?

Thanks in advance for any pointers!

**Comment by sylouuu** [comment]
Hello @HoorayFerSocks,

Hard to help you without the HTML source code associated on the page.

To assign a custom title, you can extract a portion of a text from the HTML source code and/or a fragment from the URL.

If you need, reopen the issue with more information.

Best
