### ISSUE TITLE
Selector working in console but not in Tab Modifier rule

### ISSUE THREAD

**Issue by batvink** [furybee/chrome-tab-modifier#238]
### Tab Modifier version
0.22.0

**Browser:** `Chrome` or `Opera`
Chrome

**Extension version:** `X.Y.Z`
0.22.0

### Expected behavior

A selctor that works in console will work as a rule

### Actual behavior

I try this in console:
_document.querySelector('div.customer-title-text').innerText_
It works.

I add this as a rule:
_{div.customer-title-text}_
It doesn't work

It seems that it is expressed as 
_document.querySelector('div.customer-title-text').childNodes[0].innerText_
which is invalid

**Comment by SoundIKS** [comment]
Same problem.
