### ISSUE TITLE
Similar extensions ?

### ISSUE THREAD

**Issue by capellavacancies** [furybee/chrome-tab-modifier#240]
Hello, I like this extension but I wonder if there's something similar being still developed

thanks

**Comment by sylouuu** [comment]
Hello @capellavacancies,

Maybe [Simple Tab Renamer](https://chromewebstore.google.com/detail/simple-tab-renamer/ailhpmlejogfdcpoflidmobgkgdemaog) or [Chrome Tab Renamer](https://chromewebstore.google.com/detail/chrome-tab-renamer/jbjkejjogkedpjendhaccnccmeiafied).

Best
