### ISSUE TITLE
Regex problem - the Regex or TM at fault?

### ISSUE THREAD

**Issue by paul1149** [furybee/chrome-tab-modifier#241]
Hello,
(Sorry to see this extension coasting for now, but thank for a great extension.)

I'm wondering if this is my Regex at fault or whether there is some anomaly within TM.

At Regexr.com (https://regexr.com/6un59), The RegEx:

`https:\/\/www\.biblegateway\.com\/passage\/\?search=.*version=(?!MOUNCE)(?!.*;).*`

Does hit:

`https://www.biblegateway.com/passage/?search=John+3&version=NASB`

But it is not working in TM.

It's very possible the fault is mine, but I don't see it at this point. Thanks.

**Comment by ChadOwens777-Jacobs** [comment]
A recent update cause TM to stop updating my procore tabs.

`app[.]procore[.]com/754712/project/daily_log/list? 
`
and a URL matcher field with

`date=[0-9]{4}-([0-9]{2}-[0-9]{2}) `

Allowed a "Tab Title" of 
<String> $1     

To create a tab label of something like "GMP1 05/21" for the procore daily entry of May 21st

This allowed easy parsing between projects and specific date.

This stopped working due after a recent update.

Unsure why, but it's been working for like a year.
