### ISSUE TITLE
Manifest v3?

### ISSUE THREAD

**Issue by PoorChameleon** [furybee/chrome-tab-modifier#242]
It would be awesome if someone has or is able to update this to v3, even if nothing else is updated.

Currently it seems that tab pin addons at least sort of exist(?), however I am not able to find any favicon setting addons with v3 which would be a nice feature even with a partial upgrade or a different addon. The latest ones I was able to find were last updated 5+ years ago.

Does anyone have suggestions or as an example suggestions for v3 addons that set favicon for a specific url (or any other currently existing feature)?

**Comment by sylouuu** [comment]
Hello @PoorChameleon,

The migration to Manifest v3 is completed and released.

Bests
