### ISSUE TITLE
How to stop the warning: Leave site? Changes may not be saved.

### ISSUE THREAD

**Issue by trumann1321** [furybee/chrome-tab-modifier#244]
Tab Modifier works well for me as far as renaming tabs. However, since installing it, I get incessant warning popups that say: "Leave site? Changes may not be saved."
After an internet search for how to fix this, I found that others had the same experience when using the Tab Modifier extension. I uninstalled the extension, and the problem stopped. I reinstalled it, and the problem began again. The popups appear across all open tags, not only those tagged by the Tab Modifier.
Is there a way to fix this on my end? I'm only so-so at computers, but can follow detailed instructions. Or can you guys fix this on your end? Your extension is the only one that actually renames tabs effectively. Glad so many people can use it without a glitch.
Thanks in advance

**Comment by sylouuu** [comment]
Hi @trumann1321,

Please refer to https://github.com/sylouuu/chrome-tab-modifier/issues/83

Best
