### ISSUE TITLE
[BUG] Use first rule when multiple not working

### ISSUE THREAD

**Issue by AurelienPOLLET** [furybee/chrome-tab-modifier#245]
### Tab Modifier version

**Browser:** `Chrome`

**Extension version:** `0.22.0`

### Expected behavior

If an URL respect multiple rules, only the first one is triggered.

### Actual behavior

The tab apply the second rule (? and the first ?)

### Steps to reproduce the behavior

URL used : https://github.com/XXX/repo/issue/100

**First rule**
Detection regex : `https:\/\/github.com\/XXX\/.*\/issues\/.*`
Title : {title}

**Second rule**
Detection Contains : https://github.com/XXX/repo
Title : repo

(tested to break the second rule to confirm the first one is correct and it is)

**Comment by TAGC** [comment]
I can confirm, high-priority "regex" rules don't get applied if a lower-priority "contains" rule also matches.

**Comment by TAGC** [comment]
See also #111.

**Comment by sylouuu** [comment]
Hi @AurelienPOLLET,

Fixed in the latest release, hope that helps!

Bests
