### ISSUE TITLE
Question: How to pull h2 using selector

### ISSUE THREAD

**Issue by andrew-manger** [furybee/chrome-tab-modifier#246]
I am trying to pull through an `<h2>` element nested with some divs into the tab title, but the CSS selector text copied from the Chrome Inspector doesn't work. I've tried several variations without success. 

<img width="1223" alt="html code" src="https://user-images.githubusercontent.com/18348820/231268281-f2fb6b83-c23b-462f-b732-a00d477694c7.png">

**Comment by sylouuu** [comment]
Hello @andrew-manger,

Please provide the HTML here so we can copy/past it and try in https://jsfiddle.net/ to give you the right selector to set.

Best
