### ISSUE TITLE
Contact Tab Modifier

### ISSUE THREAD

**Issue by jeoup87** [furybee/chrome-tab-modifier#250]
Hello,
I want to buy your Tab Modifier extension.
Payment by escrow.com
Please contact me by email :) [jeoup87@gmail.com](mailto:jeoup87@gmail.com)
Sorry for writing in Issues

**Comment by andrew-manger** [comment]
Did you get any response @jeoup87 ?

**Comment by jeoup87** [comment]
> andrew-manger

no ;(

**Comment by sylouuu** [comment]
No thx
