### ISSUE TITLE
Can't use different names for tabs with the same URL

### ISSUE THREAD

**Issue by morninj** [furybee/chrome-tab-modifier#251]
### Tab Modifier version

**Browser:** `Chrome` 

**Extension version:** 0.22.0

### Expected behavior

I have two tabs with the same URL. I want to name them differently.

### Actual behavior

I try to give them different names, but I can't. The name I enter in the second tab is automatically replaced by the name from the first tab.

**Comment by martic** [comment]
If the pages have different content use the selectors:
You can inject any DOM content with {selector}. Examples: {title} for website title, {h1}, {#id}, {.class}, etc.

**Comment by sylouuu** [comment]
Hello @morninj,

It's how the extension works. Please read the [Focus scope](https://github.com/furybee/chrome-tab-modifier?tab=readme-ov-file#focused-scope) of the README.

Best
