### ISSUE TITLE
This Disables RightInbox Extension 

### ISSUE THREAD

**Issue by arokyne** [furybee/chrome-tab-modifier#252]
I noticed that when chrome-tab-modifier is activated, my [RightInbox](https://chrome.google.com/webstore/detail/rightinbox-email-reminder/mflnemhkomgploogccdmcloekbloobgb) extension stopped working. Seems odd since they are probably not related in regards to their functionality. I can't really work without RightInbox since it's a huge part of my workflow. But I would love to also use chrome-tab-modifier.

Any advice? Do I have to only use one or the other?

**Comment by sylouuu** [comment]
Hi @arokyne,

Do you still experience the issue regarding the major version released?

Bests
