### ISSUE TITLE
Tab Modifier seems to lock up Opera Browser when used with Tree Tabs

### ISSUE THREAD

**Issue by smgolden** [furybee/chrome-tab-modifier#254]
_In case of bug report, please fill this template and remove italic lines_
_Otherwise, clear all and type :)_

### Tab Modifier version
0.22.0

**Browser:** `Chrome` or `Opera`
Opera

**Extension version:** `X.Y.Z`
?

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Expected behavior
That it would be compatible and not Freeze Opera.

I used the Tab Modifier extension to modify tab names based on order ID in the URL.  If it finds the order ID, it calls it Order #6 for example.

It seems that whenever I open more than one tab having that same order id in the URL, (Tab Modifier labels two tabs with the same label) it causes Opera to freeze up.

I am using Tree Tabs also.

1. I open an order from the TEMU shopping site.
2. I click on a link inside that order which opens another tab.  Since it is associated with that order, the order ID is present in both tabs.  At that time, there are two tabs with the same label.  Within moments after that, Opera freezes.

I have disabled Tab Modifier.  I have not experienced the freeze since I disabled Tab Modifier.

I have a Sysinternals Process Explorer minidump of the crash.  It can be opened with the Microsoft WinDbg tool.  Your process doesn't allow upload of dmp files.

**Comment by sylouuu** [comment]
Hi @smgolden,

Can you try again with the latest version?

Bests

**Comment by smgolden** [comment]
No.  I'm done with Opera.


Sincerely,
Stephen Golden 

    On Friday, June 7, 2024 at 11:26:37 AM CDT, Syl ***@***.***> wrote:  
 
 


Hi @smgolden,

Can you try again with the latest version?

Bests
