### ISSUE TITLE
cannot change tab name for server http://127.0.0.1:8188/

### ISSUE THREAD

**Issue by rafstahelin** [furybee/chrome-tab-modifier#259]
### Tab Modifier version

**Browser:** `Chrome` or `Opera`
Chrome

**Extension version:** `X.Y.Z`
0.22.0

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

### Expected behavior

_What do you expect?_
to rename tab for webapp  server 
for example:
Rule created from right-click (127.0.0.1:8188/...) | Contains | http://127.0.0.1:8188/
All other tab renaming work. But not for this use case

### Actual behavior

_What actually happen?_
tab name does not change to modified name

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. right click on tab
2. change name
3. enter

Is there a way to allow each instance of http://127.0.0.1:8188/ to have a unique title name?

**Comment by sebastienfontaine** [comment]
Hello,

It works for me.

<img width="917" alt="image" src="https://github.com/furybee/chrome-tab-modifier/assets/45472257/c863f4b3-3491-4af0-81d6-c2316242e8df">

Best regards,

**Comment by sebastienfontaine** [comment]
Hello,

It works for me.

<img width="917" alt="image" src="https://github.com/furybee/chrome-tab-modifier/assets/45472257/c863f4b3-3491-4af0-81d6-c2316242e8df">

Best regards,
