### ISSUE TITLE
Does not work with Notion web app 

### ISSUE THREAD

**Issue by kaledaddy** [furybee/chrome-tab-modifier#260]
_In case of bug report, please fill this template and remove italic lines_

### Tab Modifier version

**Browser:** `Chrome`

**Extension version:** `X.Y.Z`

chrome-extension://hcbgadmbdkiilgpifjgcakjehmafcjai/html/options.html#/settings

www.notion.so

### Expected behavior

For this to change the name of the tab
### Actual behavior

It changes the tab name for a few seconds and then reverts back to the original name. I think this is because Notion is written in javascript?

### Steps to reproduce the behavior

Open a page in www.notion.so and try to rename it

**Comment by joshlewis** [comment]
Seconded! This plugin needs some logic that will watch the page title and overwrite it again and again with the chosen title. See here for more: https://stackoverflow.com/questions/2497200/how-to-listen-for-changes-to-the-title-element

**Comment by joshlewis** [comment]
As a stopgap, I made a JavaScript bookmarklet that will keep the tab's name set until the page is reloaded or navigated to a new page. Might be helpful to some people. If you save this as the "URL" in a bookmark, clicking the bookmark will as you to input the tab name you want, and there you go.

In one line, for a bookmarklet:
```
javascript: (() => { window.specialTitle = prompt('Tab name'); new MutationObserver(function() { if (document.title !== window.specialTitle) {document.title = window.specialTitle;} }).observe(document.querySelector('title'),{ childList: true }); document.title = window.specialTitle; })();
```

Or easier to read:

```
javascript: (() => { 
    window.specialTitle = prompt('Tab name');
    
    new MutationObserver(function() {
        if (document.title !== window.specialTitle) {
            document.title = window.specialTitle;
        } }).observe(document.querySelector('title'),{ childList: true }); 
    
    document.title = window.specialTitle; 
})();
```

**Comment by sylouuu** [comment]
Hi @kaledaddy,

Seems to work now on Notion since the 1.0 is out!

Bests
