### ISSUE TITLE
Cannot add custom icon

### ISSUE THREAD

**Issue by 1Resonant** [furybee/chrome-tab-modifier#269]
### Tab Modifier version

**Browser:** `Chrome`

**Extension version:** `1.0.1`

### Expected behavior

I expect the custom icon I've set in a rule to be used for the tabs governed by that rule after setting a URL and clicking Save on the Edit modal.

### Actual behavior

After setting a custom icon URL, the icon is not shown after saving and appears to have been forgotten when I open the rule's Edit modal a second time.

The icon is then _not_ used for tabs governed by the rule.

### Steps to reproduce the behavior

_Please describe the steps to help me to reproduce the actual behavior_

1. Open a rule to be edited
2. Click "Use custom icon" hot text
3. Paste or type in a valid image URL
    - The icon shows up to the left of the field
4. Click Save button to confirm-close the Edit modal

**Comment by naadeiii** [comment]
Same issue + steps to replicate:
**Browser:** `Version 125.0.6422.142 (Official Build) (arm64)`
**Extension version:** `1.0.1`

**Comment by pablommu** [comment]
Same issue + steps to replicate:
Browser: Microsoft Edge for Business - Version 125.0.2535.92 (Official build) (arm64)
Extension version: 1.0.2

**Comment by jthomascolombo** [comment]
Thanks for the quick fix! When will the 1.0.3 update be available in the Chrome Web Store?

**Comment by sylouuu** [comment]
> Thanks for the quick fix! When will the 1.0.3 update be available in the Chrome Web Store?

It takes approx. a day. :/
