### ISSUE TITLE
"Starts With" detection type never matches

### ISSUE THREAD

**Issue by ScottLangham** [furybee/chrome-tab-modifier#285]
**Describe the bug**
Detection type of "Starts With" doesn't match. Old rules (created with previous version of Tab Modifier) that have a detection type of "Starts" (note... no "With") still work, but if I edit one and it changes to "Starts With" it stops matching.

**To Reproduce**
1. Use previous version of Tab Modifier
2. Create a rule that has a detection type of "Starts"
3. Get latest version of Tab Modifier
4. Create a rule that has a detection type of "Starts With"  ("Starts" is no longer available)

**Actual behaviour**
The old rule with detection type "Starts" still works.
New rules with detection type "Starts With" do not match.

**Expected behavior**
One of:
 - The new version of Tab Modifier to have still use "Starts" instead of "Starts With"
 - The new "Starts With" to match urls. And any old rules that used a detection type of "Starts" to be upgraded to use a detection type of "Starts With".

**Screenshots**
A rule created with old Tab Modifier that still works:
![image](https://github.com/furybee/chrome-tab-modifier/assets/11654035/e906e5fa-7b54-4567-b0d5-203553f8af0b)

A rule created with new Tab Modifier that does not work:
![image](https://github.com/furybee/chrome-tab-modifier/assets/11654035/f15b1ef9-a09f-4bef-802e-4db8e6a3303a)

**Extension version:** `1.0.2`

**Comment by ScottLangham** [comment]
Workaround is to use "Contains"

**Comment by sebastienfontaine** [comment]
Hello,

Thank you for reporting this issue. I wanted to let you know that the fix will be included in version 1.0.3. This update is currently under review in the Chrome Web Store and should be available very soon.

Thank you for your patience and support.

**Comment by ScottLangham** [comment]
Brilliant, thanks very much
________________________________
