### ISSUE TITLE
Group name is not set after reordering a tab

### ISSUE THREAD

**Issue by babeuloula** [furybee/chrome-tab-modifier#308]
**Describe the bug**

Hello,

When you have a tab in a group and you reorder it, the group is not set after drag off.

**To Reproduce**
1. Create a group
2. Go to the page of the matched group
3. Reorder your tab
4. See error. You need to refresh the tab to see the group

**Expected behavior**
When I reorder the tab, I need to keep the group

**Extension version:** `1.0.5`

**Comment by sebastienfontaine** [comment]
Related PR : https://github.com/furybee/chrome-tab-modifier/pull/313
