### ISSUE TITLE
Duplicate-function leads to confusion/trouble - suspect it duplicates internal ID

### ISSUE THREAD

**Issue by mortensimon** [furybee/chrome-tab-modifier#309]
About my environment:
I am using v1.05 of TM in Chrome in Windows. I have around 60 rules defined. I have tested to have one group used by a few rules. Many of the rules have the same name and the same TAB name, only the color varies. The URL-fragment is unique in all rules. 

About my issue:
I like to use the duplicate button, to create the same rule, but change color and URL-fragment. When I press the dupliate-button, a new rule is created at the bottom of the list (which is a little annoying - since moving the rule up a long list is now veeery cumbersome). Then I go to the bottom of the list to modify the duplicate. But when I save, it seems like it is the *original* rule which has been saved. This behavior seems to be somewhat consistent. It furthermore seems like when I have made a lot of duplicates, these rules are somehow linked - and I always change another rule than the one I want to!! I suspect that duplicate of a rule duplicates too much...also the internal ID. 

Also some thoughts in general:
* Nice to have groups - but if you could offer a way to open all tabs in a group, then you would have added something to a feature that I already found in Chrome.
* A list of 60 rules is a bit hard to manage. Especially now that moving rules up/down has become so clumsy (click, click, click) - before you could drag/drop. Is it possible to consider some division of the list? Perhaps use the group concept to provide a list *pr* group - so I could work within a group list, which would be much shorter.
* It's not very useful that I *have* to fill out *both* Rule Name and Tab Name. There should be an option to set the to the same - or rather skip Rule Name altogether. 

I will donate to the cause! I can see that something is happening, but I am afraid TM has become worse lately.... even though the group-feature could potentially be something useful. I feel the potential is not realized yet.

**Comment by sebastienfontaine** [comment]
Thank you for your detailed feedback. Here are the actions we will take to address your issues:

### Duplication Issue
- **Unique ID:** Fix the duplication process to ensure each new rule has a unique ID.
- **Placement Improvement:** Improve the placement of duplicated rules to a more convenient position in the list.

### Rule Management
- **Drag-and-Drop:** Reinstate drag-and-drop functionality for easier rule rearrangement.
- **List Division:** Explore options to divide the rule list into smaller, group-based lists for better manageability.

### Rule and Tab Names
- **Auto-Set Names:** Add an option to automatically set the Rule Name and Tab Name to be identical or eliminate the need to fill out the Rule Name.

### Group Enhancements
- **Open All Tabs:** Develop a feature to open all tabs within a group simultaneously.

Thank you for your constructive suggestions. They help us improve TM continuously. If you have further suggestions or need assistance, please let us know!

**Comment by mortensimon** [comment]
Thanks a lot for picking up on this! I have another idea, which you can consider if it's any good: What if TM could access the bookmarks and generate rules for each? It should perhaps be "semi-automatic": a list of suggested rules, you set the color and the TAB name of those you want to have TM for. That could perhaps make it faster to set up many TM-rules. Today I have to both make bookmarks and TM rules. Well, as I said - just an idea.

**Comment by sebastienfontaine** [comment]
Thank you for your feedback and the suggestions provided! I am closing this issue as all reported bugs have been resolved. I will be reviewing and implementing the suggestions to the best of our capabilities. Looking forward to enhancing our tool with your valuable input. Stay tuned for updates! 😊

## Duplication Issue
* ✅ **Unique ID:** Fix the duplication process to ensure each new rule has a unique ID.
* ✅ **Placement Improvement:** Improve the placement of duplicated rules to a more convenient position in the list.

## Rule Management
* ✅ **Drag-and-Drop:** Reinstate drag-and-drop functionality for easier rule rearrangement.
* 🎤 **List Division:** Explore options to divide the rule list into smaller, group-based lists for better manageability.

Rule and Tab Names
* 🎤 **Auto-Set Names:** Add an option to automatically set the Rule Name and Tab Name to be identical or eliminate the need to fill out the Rule Name.

## Group Enhancements
* 🎤 **Open All Tabs:** Develop a feature to open all tabs within a group simultaneously.

## Bookmarks
- 🎤 **Integrate access to bookmarks in TM** - Suggest that TM (likely an application or tool) could access the user's bookmarks.
- 🎤 **Generate semi-automatic rules for each bookmark** - The tool should be able to suggest rules based on the user's existing bookmarks.
- 🎤 **Allow the user to customize suggested rules** - The user should be able to set the color and the tab name for the TM rules they want to apply.
- 🎤 **Simplify the setup of TM rules** - Currently, the user has to create both bookmarks and TM rules. The idea would be to make this process quicker and more efficient.

**Comment by sebastienfontaine** [comment]
We can continue the discussion here : https://github.com/furybee/chrome-tab-modifier/discussions/324
