### ISSUE TITLE
Regression?  Prior behavior for Unique was to the pattern, not the full URL of a page

### ISSUE THREAD

**Issue by trey-pindrop** [furybee/chrome-tab-modifier#310]
**Describe the bug**
Prior to version 1.0.5, setting the Unique flag on a rule would keep any page matching the URL fragment pattern in the same tab.  Now, in version 1.0.5 Unique considers the entire URL in the address bar for uniqueness, which spawns unnecessary and undesirable tabs for common sites.

I relied on the prior behavior to keep the number of tabs I have open for common sites/tasks in their own tabs.

**To Reproduce**
1. Create a rule with URL fragment that should match many sub-pages
2. Set the Unique flag on this rule
3. Navigate to one page that matches the URL fragment for this rule.
4. Navigate to another, different page that matches the URL fragment for this rule.
5. Observe that you now have two tabs open that match this URL fragment.

**Expected behavior**
After following the five steps above, there should only be one tab open matching this rule's URL fragment.

**Screenshots**
I have a rule with `STARTS WITH` detection for the URL fragment:  `https://pdrop.atlassian.net/browse/`.  Previously, the Unique flag would keep all of the JIra issues I navigate to in the same tab (as long as they follow this browse URL fragment).  Now, two different pages produce two different tabs, instead of the desired one tab.

Here's the screenshot of the rule configuration:  
![Screenshot 2024-06-20 at 12 00 06](https://github.com/furybee/chrome-tab-modifier/assets/17730305/9b128930-034b-4bc4-9b39-03949b035bcc)

Here are the screenshots demonstrating two different full URLs, but matching this pattern (two tabs are shown on the left):
![Screenshot 2024-06-20 at 12 04 20](https://github.com/furybee/chrome-tab-modifier/assets/17730305/afe997bf-cbce-42a0-927f-6ef7c6142323)
![Screenshot 2024-06-20 at 12 04 10](https://github.com/furybee/chrome-tab-modifier/assets/17730305/5d8cc2fb-f2f6-4de8-9223-e3b0929488a7)

**Extension version:** `1.0.5`

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

**Additional context**
Nothing more, everything should be above.

**Comment by sebastienfontaine** [comment]
Hello, 

We will work on a fix for this issue. 

Thank you for bringing it to our attention.

**Comment by sebastienfontaine** [comment]
Related PR : https://github.com/furybee/chrome-tab-modifier/pull/312
