### ISSUE TITLE
Tab Title of the Rule is overwritten by the Actual Website Title after page load completes.

### ISSUE THREAD

**Issue by vikp2** [furybee/chrome-tab-modifier#323]
Tab Title of the Rule is overwritten by the Actual Website Title after page load completes.

It first applies the Title mentioned of the Rule, but after the page load is complete, it shows the Website Title and not the Rule Title.

It happens on websites which shows Stock Market Charts. Issue is replicated on TradingView.com.

Open any Stock chart on TradingView.com, this issue happens.

This is happening only from today (25-Jun-2024). It was working fine earlier. I was using "0.22.0" version. The new version has this issue.

NOTE - The icon on the Title still applies properly as per mentioned in the Rule.

**Comment by vikp2** [comment]
Screenshot of the Rule is attached for TradingView.com
![25-June-2024__23-27_2585](https://github.com/furybee/chrome-tab-modifier/assets/173818218/811b716a-3aa6-47ef-a2d4-4998f7f2aa6e)

**Comment by vikp2** [comment]
Thanks for such a quick response. But in all 3 browsers - Opera, Edge and Chrome, still only older version is available.

Please provide some reference website so that we can find out how we can update the latest bug fix in our Browser Extension.

Many of us are non-technical users :)

**Comment by sebastienfontaine** [comment]
Sorry for the confusion. The process is automatic when we merge the fix. However, we are going to change our approach by creating a branch for each release. We will merge the release branch once it is published/validated on the store, which will close all issues at once.

**Comment by sylouuu** [comment]
@vikp2 Yes, unfortunately Web Stores moderators are very slow to validate extensions. We usually have to wait days or weeks after publishing a new version. If you are non-technical user, you won't be able to try the unpublished version.

Be patient then!

Bests

**Comment by vikp2** [comment]
@sebastienfontaine , @sylouuu - Thank you Team. Will wait.
