### ISSUE TITLE
Favicon briefly changes to my specified one, but then changes back once page loads

### ISSUE THREAD

**Issue by gerrymiller** [furybee/chrome-tab-modifier#326]
**Describe the bug**
Chrome tab modifier has been AWESOME, thank you! I recently updated to Brave [Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64)](https://brave.com/latest/), and I'm suddenly back to the Favicon for the site, rather than the one I want. I see the Favicon I specified in the rules briefly, but the tab reverts to the site's Favicon once the page is fully loaded.

**To Reproduce**
1. Using the latest version of Brave browser, go to a website that matches a Chrome tab modifier rule.
2. Watch how the tab briefly shows the correctly specified Favicon, then reverts to the site's Favicon.

**Expected behavior**
Prior to updating Brave this morning, the tab correctly showed my specified Favicon.

**Screenshots**
[Here's a link to a video of this problem in action.](https://app.screencast.com/71JbFPQ34hH6P) Note that the Favicon briefly includes "TW," as I've configured, but then quickly reverts to the default Favicon once the page is loaded. This was working prior to updating Brave this morning, and I've made no other config changes.

**Extension version:** `1.0.6`

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

**Comment by sylouuu** [comment]
Hi @gerrymiller,

1. Do you have the same behavior on other sites?
2. Do you confirm the same website works on Chrome so the issue is only targeted on Brave?

Bests

**Comment by gerrymiller** [comment]
Thank you, @sylouuu. I am not seeing this behavior on other sites (e.g., https://oxygen.cloudticity.com), so it may be isolated just to https://teamwork.cloudticity.com.

The issue with https://teamwork.cloudticity.com shows on the latest versions of both Brave and Chrome.

Warm regards,
- Gerry

**Comment by sebastienfontaine** [comment]
Hi @gerrymiller, 

Do you still have the bug with version 1.0.7, please?

Regards,

**Comment by gerrymiller** [comment]
It's working with v1.0.7! Thank you.

**Comment by sebastienfontaine** [comment]
That's great to hear! Thank you for letting us know.
