### ISSUE TITLE
Update has deleted all current rules

### ISSUE THREAD

**Issue by martic** [furybee/chrome-tab-modifier#331]
**Describe the bug**
All my rules are gone with the recent update.

**Expected behavior**
Rules to carry over to new version after auto update.

This is a fantastic extension; I have spent many hours perfection my rules.
I had the perfect gmail rules brining in tags and email addresses.
It was perfect for my automated timesheet collection.

But now its gone. 

Can you give me hits of what the previous rules config files might look like so I can do a search or find it in a back up.

**Comment by martic** [comment]
After I created a new rule, all the previous rules re-appeared.
Rules have now been backed up.
Thanks for a great extension.

If anyone is interested in getting a useful tab name from gmail try this:
    [Email:{.ain a}] {H2.hP} [from] {.gD span} [to] {.acZ.xD [email]} [tag] {.ahR div[name^="C/"]}
It is not a great tab name if you don't have an email open, but I'm only tracking open emails.
Result:
Gmail [Email:Inbox] Changes Required [from] Harry Smith [to] me [tag] C/SmithCo

Rules in gmail that tags clients based on their email domain, all the clients are under the C/ tag

**Comment by sebastienfontaine** [comment]
Hello,

Thank you for reporting the issue and providing such detailed feedback.

We're glad to hear that the previous rules reappeared after creating a new rule and that everything is back to normal. It's great that you've backed up your rules as well.

We appreciate your patience and your kind words about the extension. If you encounter any more issues or have further suggestions, please feel free to reach out.

Best regards,
