### ISSUE TITLE
Two groups with same name, but different color

### ISSUE THREAD

**Issue by mortensimon** [furybee/chrome-tab-modifier#333]
My use-case for TM is to have tabs for approx 60-70 different URLs to servers which all would look identical if not for TM. One *very* important dimension is production vs test. Naturally, I would use color (red/yellow) to separate the two environments - but the same names. That works fine for TM rules, but not for groups (understandable, since group concept is pretty new).

The issue is this:

Tab Rule 1: "S1" (red) - (URL fragment "prodserver.com")
Tab Rule 2: "S1" (yellow) - (URL fragment "testserver.com")

Group 1: "G" (red);
Group 2: "G" (yellow)

TabRule1 is placed in Group 1
TabRule2 is placed in Group 2

If you open the URL "prodserver.com" - Group 1 will be displayed. After that, you open "testserver.com" and both! tabs will be added to Group 2 (yellow). If you open "prodserver.com" again, all three tabs will be added to Group 1...and so on.

**Comment by sebastienfontaine** [comment]
Thanks for your feedback. I've implemented a fix, which will only work if the colors for the same group name are different. This will resolve the issue in release 1.0.9.

To avoid mixing tabs between groups, ensure each group has a unique color. Even if groups share the same name, distinct colors will keep them separate. This way, your "prod" and "test" environments won't get confused in the tab management.
