### ISSUE TITLE
@1 tokens can appear in title

### ISSUE THREAD

**Issue by stubar** [furybee/chrome-tab-modifier#343]
**Describe the bug**
When a regex capturing group doesn't capture, it's token shouldn't render in the title

**To Reproduce**
1. Create an advanced title matcher
2. Use regex `(.*)some text I do not want in my title(.*)`
3. use title of `@1@2`
4. Title shows "@1 suffix text that matched via 2nd capturing group"

**Expected behavior**
When there is no match of a capturing group, do not render it's token

**Extension version:** `1.0.8`

_Can be found here: chrome://extensions/?id=hcbgadmbdkiilgpifjgcakjehmafcjai_

**Comment by sebastienfontaine** [comment]
Hi ! 

This won't be fixed as it could lead to other problems. The simplest and most effective solution is to just remove @1 from the title. 

Thank you for your understanding!

--- 

![CleanShot 2024-07-03 at 15 21 42](https://github.com/furybee/chrome-tab-modifier/assets/45472257/958f1de9-325f-4074-9a2c-b64ce8c4cfb9)

💡 You can test your regex directly in the window by pressing the Help button in the top right corner.

![CleanShot 2024-07-03 at 15 23 20](https://github.com/furybee/chrome-tab-modifier/assets/45472257/9eda4a65-391a-4c36-96e7-a52eccc96ef2)
