### ISSUE TITLE
cannot import settings which is exported before

### ISSUE THREAD

**Issue by ladyrick** [furybee/chrome-tab-modifier#347]
**Describe the bug**
cannot import settings which is exported before

When in `mergeConfig()`, you try to read `groups.length`. But in previous version, there are no such thing called `groups`. So it's a bug.

**Comment by sebastienfontaine** [comment]
Hi,

Thank you for reporting this issue. We have identified the bug. This will be resolved in the upcoming [1.0.10](https://github.com/furybee/chrome-tab-modifier/pull/348) update, currently being published on the store.

Best regards,
