### ISSUE TITLE
Why on earth do my priorly exported .json files no longer work?

### ISSUE THREAD

**Issue by Dave3848** [furybee/chrome-tab-modifier#353]
Is it due to the new version/design or whatever? If so, then why on earth does it not support the prior exports??? This is super infuriating, as I've currently got a huge backup file, I can't use!

**Comment by Dave3848** [comment]
Alright, so it's super easy to fix, but this was still pretty stressful. I need a smoke.

**Comment by sylouuu** [comment]
Can you detail for other users how did you fix it?

**Comment by Dave3848** [comment]
> Can you detail for other users how did you fix it?

Sure, you just gotta add '"groups": [],' (no single quotes) after the beginning bracket inside for example Notepad. Then the import will work.
