### ISSUE TITLE
nextjs.org website crash 

### ISSUE THREAD

**Issue by hh9515** [furybee/chrome-tab-modifier#354]
**Describe the bug**
nextjs.org crash using this extension

**To Reproduce**
1. using this rule 
<img width="937" alt="image" src="https://github.com/user-attachments/assets/cdc7f830-6b18-4ef0-8c5d-8279aea4d51f">

3. go to https://nextjs.org/ 
4. click 'showcase' or 'docs' in top section
5. the website crash

**Expected behavior**
im using this rule in all websites , when browsing nextjs , the website crash

**Screenshots**
<img width="791" alt="image" src="https://github.com/user-attachments/assets/aefc1d37-32cc-405b-9e42-8743d6b5381c">

**Extension version:** `X.Y.Z`
latest

**Additional context**
maybe should add a feature to exclude some website

**Comment by sebastienfontaine** [comment]
Hello,

Thank you for reporting this bug. It will be resolved in the next release: 1.0.11.

Best regards,
