### ISSUE TITLE
Problem with Chrome Security (Chrome 130+)

### ISSUE THREAD

**Issue by sylouuu** [furybee/chrome-tab-modifier#378]
### Discussed in https://github.com/furybee/chrome-tab-modifier/discussions/377

<div type='discussions-op-text'>

<sup>Originally posted by **ciltocruz** September 11, 2024</sup>
Hello.

I bought a new computer and installed Chrome Tab Modifier.

It doesn't work.

The error I get is this:

```
Refused to load the script 'chrome-extension://e98cbfeb-3ded-4047-b873-61162833edcc/assets/content.js-D8gZ41FF.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

Is it my computer or is there a Chrome setting I need to change? I'm not sure where the problem is.
I don't know if it has anything to do with the new versions of the v3 manifest for chrome extensions

My Chrome version is:
Version 130.0.6699.3 (Official Build)

Thanks!</div>

**Comment by sebastienfontaine** [comment]
Hello,

Thank you for your report. A fix will be available in version `1.0.12`. The release is currently under validation by the Chrome Web Store team and will be available soon.

Chrome (130+) has introduced additional restrictions for CSP (Content Security Policy).

Best regards,

**Comment by ciltocruz** [comment]
Thanks!

**Comment by ciltocruz** [comment]
What is known about Chrome Web Store team validation?

**Comment by sebastienfontaine** [comment]
Sorry I closed the issue too quickly :D It's still being validated. This will surely be validated this week

**Comment by ciltocruz** [comment]
It's working again!! Thanks!!
