### ISSUE TITLE
Feature Request: More Colors for Groups

### ISSUE THREAD

**Issue by ekk88d** [furybee/chrome-tab-modifier#384]
Please introduce the feature to select and store custom colors for Groups.

I use your extension a ton, and need more colors for Groups. Red looks similar to orange, which looks similar to yellow.
Dark red, for example, would offset the other colors better, but the ability to specify custom colors for Groups would be much appreciated.

**Comment by sebastienfontaine** [comment]
Unfortunately, it’s not possible to add custom colors at this time, as the available colors are hardcoded in Chrome. You can view the list of predefined colors here: https://developer.chrome.com/docs/extensions/reference/api/tabGroups#enum. 

<img width="351" alt="image" src="https://github.com/user-attachments/assets/bde6b4a4-a1da-48ed-a714-4aadfad00a41">


Thank you for your understanding!
