### ISSUE TITLE
Rule on Edge not work

### ISSUE THREAD

**Issue by davidxu5945** [furybee/chrome-tab-modifier#402]
**Describe the bug**
Rule on Edge not work

**To Reproduce**
1. set rule Name  `test`
2. same rule on chrome is work

**Expected behavior**
rename tab name on edge

**Extension version:** `1.0.11`

<img width="894" alt="image" src="https://github.com/user-attachments/assets/b7ee9528-579f-4c01-84be-cf216e1b62b9">

**Comment by quadrotony** [comment]
Opera One(version: 115.0.5322.36)

same issue from today
rules active but all stopped to work

**Comment by tianchen-zhang** [comment]
This appears to be a problem related to CSP violations on browsers with Chromium version >= 130, since the same issue occurs with various extensions.

**Comment by tianchen-zhang** [comment]
Well, the same problem has already been discussed in issue #378. Upgrading the extension to version 1.0.12 should fix the problem.

**Comment by quadrotony** [comment]
> Well, the same problem has already been discussed in issue #378. Upgrading the extension to version 1.0.12 should fix the problem.

there is no button to upgrade, i have 1.0.4 in Opera
if i install 1.0.12 its cimpletely separate extension and all my tab settings not transfer there WHAT THE FUCK?

**Comment by sebastienfontaine** [comment]
Hello, you can export your rules in Settings > Backup > Export. 

For Opera, Edge, etc., validation is very slow. We are doing our best to make them more responsive, but our messages remain unanswered. 🥲

We will keep you updated on any developments.

**Comment by sylouuu** [comment]
> Opera One(version: 115.0.5322.36)
> 
> same issue from today rules active but all stopped to work

Side note: Opera moderators are no longer active to validate Tab Modifier package submissions since June 2024... If you want to keep working with the latest TM version, you need to use a [different supported browser](https://github.com/furybee/chrome-tab-modifier?tab=readme-ov-file#installation).
