### ISSUE TITLE
Problem with Slack

### ISSUE THREAD

**Issue by dzg** [furybee/chrome-tab-modifier#64]
Great extension, thanks!!

My issue is with Slack -- I have a rule to append `•wh•` to all my tabs, and this is the result:

![image](https://cloud.githubusercontent.com/assets/466557/23131554/1a12cab8-f793-11e6-9cff-9f37763a0017.png)

(The rule is match any and use `{title}•wh•`)

**Comment by sylouuu** [comment]
Hi @dzg,

Thanks for reporting this.

I'm surprised because the extension already handles websites that update its title in real-time like GMail, Twitter...

**Comment by MartinLichtblau** [comment]
@dzg My [forked version](https://github.com/MartinLichtblau/chrome-tab-modifier) can do that.
