### ISSUE TITLE
problem with url encoding

### ISSUE THREAD

**Issue by ataiger** [furybee/chrome-tab-modifier#80]
### Tab Modifier version

0.19.3

### Expected behavior

on this page `law.go.kr/법령/민법` without title tag, I want the tab to be named `민법`

when I put `law.go.kr\/법령\/(.+)` in url matcher, it does not match.

### Actual behavior

so I have to use `law.go.kr\/%EB%B2%95%EB%A0%B9\/(.+)` which is an encoded url. it does match.

but now the title `$1` becomes `%EB%AF%BC%EB%B2%95`, which is `민법` encoded.

is there a solution to this? thanks.

### Steps to reproduce the behavior

**Comment by sylouuu** [comment]
Hello @ataiger,

Can you give me your rule:

- URL fragment
- Title
- URL matcher

**Comment by ataiger** [comment]
URL fragment
`law.go.kr/%EB%B2%95%EB%A0%B9/`

Title
`$1`

URL matcher
`law.go.kr\/%EB%B2%95%EB%A0%B9\/(.+)`

on page `http://law.go.kr/법령/민법`,

what I want is `민법`

and what I get is `%EB%AF%BC%EB%B2%95` which is `민법` encoded.

**Comment by sylouuu** [comment]
Why you don't set URL fragment as `http://law.go.kr/법령/민법`?

I thought you specified:

- URL fragment: `http://law.go.kr/법령/민법`
- Title: `$1`
- URL matcher: `law.go.kr\/법령\/(.+)`

**Comment by ataiger** [comment]
the reason why I used `%EB%B2%95%EB%A0%B9` instead of `법령` is because it does not match. Korean letters (maybe other non-digit non-alphabet unicode letters as well) appears on chrome's omnibar as is, but when you copy and paste the whole URL to notepad or other programs, it shows encoded version of it. AFAIK chrome shows the decoded version of URL but actually processes things with the encoded version. so when I want the rule apply to `http://law.go.kr/법령/민법`, I have to put `http://law.go.kr/%EB%B2%95%EB%A0%B9/%EB%AF%BC%EB%B2%95` to URL fragment of your extension. you can try URL fragment `http://law.go.kr/법령/민법`, but it actually does not match to `http://law.go.kr/법령/민법`.

next, the reason I used `law.go.kr/%EB%B2%95%EB%A0%B9/` instead of `law.go.kr/%EB%B2%95%EB%A0%B9/%EB%AF%BC%EB%B2%95` is because I want the rule apply to all `law.go.kr/%EB%B2%95%EB%A0%B9/(the name of law)` pages cuz they link to each Korean law. not a big deal. detection is set to 'Contains'

**Comment by sylouuu** [comment]
So it's OK for you to set URL fragment to `law.go.kr/%EB%B2%95%EB%A0%B9/`? I can try to fix the issue with this config?

**Comment by ataiger** [comment]
I think it would be better if I could used decoded URL everywhere in the extension, but I do not care as far as I can rename the tab to '민법'. I think it is totally up to you. :)



2017. 4. 21. 오후 10:36 Syl <notifications@github.com> 작성:
