### ISSUE TITLE
Usability of title/URL matchers

### ISSUE THREAD

**Issue by shabino** [furybee/chrome-tab-modifier#84]
### Tab Modifier version

` 0.19.3`

I just installed this plugin today for the first time. It took me awhile to figure out how to use the title/URL matchers. At first, I didn't even notice the the regular expression input areas because they were "below the fold".  Even then, I didn't recognize them as places where I could type something because I had interpreted the grey strings "Title matcher" and "URL matcher" as static text titles for the snippets of help below.  For URL matching (which I tried at first), I'd presumed that capture groups defined in the "URL Fragment" regex (if selected vs. contains, etc.) would be the ones I'd have access to with $1, etc.

Suggestions:

1. The vertical flow of the page doesn't match my mental model.  Putting the "Title matcher" and "URL matcher" inputs above the "Title constructor" makes more sense to me because those values, if defined are used when constructing a title.

2. Some text inputs (like "Name") have example input in the text area in addition to a title.  This made it clear to me that I had the option of typing something there.  However, the "Title matcher" and "URL matcher" inputs aren't this way.  An example would have helped me to identify them as places where I could type something

I think the above two changes would have alleviated my confusion about using capture groups from the URL fragment.

**Comment by sylouuu** [comment]
Hi @shabino,

Thanks for your feedback.

I'm aware that the form is now hard to understand for a new user. Features came quickly.

The Options page needs a total rework, with a new UX (especially for the form as you described) but maybe with a new UI. Angular Material doesn't allow me to be really free about the UX, there are many limitations because of poor components.

No EAT available for a fresh Options page.

Bests

**Comment by 42degrees** [comment]
A little off-topic, but what is "EAT" in that sentence.  I have a feeling I'm missing a meme... ;-)

**Comment by sylouuu** [comment]
@42degrees It's a typo, I would say "ETA" for "Estimated Time of Arrival". :)

**Comment by 42degrees** [comment]
Well, that makes more sense ;-)
