### ISSUE TITLE
Allow tab names to change based on SPA url route changes

### ISSUE THREAD

**Issue by enlightendev** [furybee/chrome-tab-modifier#93]
Many SPA (Single Page Apps) dont refresh the page and only change a fragment of the URL to navigate within the application.

e.g. 
https://myurl.com/page#sectionone 
https://myurl.com/page#sectiontwo

I would like to be able to change tab title in this situation where as you navigate through web app only the sectionone/two part is changing.

**Comment by sylouuu** [comment]
Hi,

SPA should work if the URL changes (not the hash). I have experienced some issues by adding the hash detection before, see #39.

Bests

**Comment by MartinLichtblau** [comment]
Ohh, after investing so much time I find out that it doesn't work for my purpose. I wanna use it in google Keep to give the tab title the title of the note (as it should be). 
So TabModifier can't detect such an URL change? From _https://keep.google.com/#home_ to _https://keep.google.com/#NOTE/1mjtWioxGcc_.
If not: Please make it work for such cases.

**Comment by MartinLichtblau** [comment]
@enlightendev My [forked version](https://github.com/MartinLichtblau/chrome-tab-modifier) can do that.
